### ISSUE TITLE
Migration notes update

### ISSUE THREAD

**Issue by jmeas** [brigade/react-waypoint#106]
The release notes demonstrate migrating threshold values as such:

```jsx
// old
<Waypoint threshold={0.1} />

// new
<Waypoint bottomOffset='10%' topOffset='10%' />
```

When the correct migration is actually:

```jsx
// old
<Waypoint threshold={0.1} />

// new
<Waypoint bottomOffset='-10%' topOffset='-10%' />
```

For the reasoning behind the change, [this comment](https://github.com/brigade/react-waypoint/issues/77#issuecomment-223705419) and the short conversation that follows explains it.

**Comment by trotzig** [comment]
Whoops, sorry! I've updated the release notes. Thanks for keeping me on my toes!

**Comment by jmeas** [comment]
:v: Thanks for the quick fix.
