### ISSUE TITLE
topOffset & bottomOffset

### ISSUE THREAD

**Issue by namwkim** [brigade/react-waypoint#108]
Thanks for the useful library! 

I wonder if topOffset & bottomOffset are really working? I am using "window" as an ancestor container and I set "80%" to topOffset. Does it mean that, when my scroll is at the bottom 20% of the "window" container, the waypoint will enter? It currently enters when the scroll reaches the bottom Please update the documentation if possible. 
Thanks!
Nam

**Comment by jmeas** [comment]
I'd expect it to work like how you're describing. It should be straightforward to debug where things are diverging from your expectation with a breakpoint in this lib's source code. Do you have the time to do that?

**Comment by jmeas** [comment]
@namwkim , I think things are working as I'd expect here.

The `topOffset` only affects the top boundary of the page – not the bottom. So the behavior you're seeing where elements are entering or leaving when they reach the bottom of the page seems like what I'd expect. Setting `topOffset: 20%` means that elements are considered "inside" the viewport when they are between 80% and 100% of the page size.

If this doesn't make sense, then allow me to try to summarize the algorithm behind this lib:

There's the concept of a **top boundary** and a **bottom boundary** in React Waypoint. When you're between the boundary points, you are considered **inside**. When you are not within the boundaries, you are **outside**. The default top and bottom boundary is 0, which will represent the edge of the viewport when the ancestor is the window.

The **enter** callback is fired when an element transitions to being **inside**. The **leave** event is triggered when an element transitions to being **outside**. These events fire at both boundaries: the top and the bottom boundary.

The `topOffset` and `bottomOffset` can be used to offset the top and bottom boundaries, respectively. By moving the `topOffset`, you've only changed the behavior of that top boundary. This means that you will still see enter and leave events when elements scroll to the bottom of the viewport (remember: the bottom boundary is controlled by the `bottomOffset`). However, setting `topOffset` means that you'll also see enter and leave events when elements pass the 80% viewport mark.

**A demo**

Here's a short gif showing the behavior when `scrollableAncestor` is `window`, and `topOffset` is `"80%"`. The grey square represents the bottom 20% of the viewport.

![waypoint](https://cloud.githubusercontent.com/assets/2322305/16938759/0ea0c634-4d30-11e6-814a-1ca670384657.gif)

(you can ignore the weird rendering glitch in the gif that causes the bg of the page to turn light grey sometimes. Not sure what that is 😛 )

You can play with this example over [here](https://github.com/jmeas/react-waypoint-issue-8-example). To install:

1. clone the repo
2. run `npm install`
3. open `index.html` in your browser
4. scroll around with the console open

---

Let me know if this helps you! If it does, feel free to close this issue. If it doesn't, just let me know and I'd be happy to help out more.

**Comment by jmeas** [comment]
I drew a little diagram that tries to show the basics of the algorithm.

![untitled_artwork](https://cloud.githubusercontent.com/assets/2322305/16939123/5be12454-4d33-11e6-86b6-ad431da93bf2.png)

The top and bottom boundaries are like inverses of one another. If you're implementing a scrollspy, you can generally ignore one of them. I implemented a scroll spy and only used the top offset (with a value of `50px` – the size of the app's header).

**Comment by trotzig** [comment]
That ^^^ is just fantastic! Can we get the drawing as a PR added to the README?

**Comment by jmeas** [comment]
Hey @namwkim , I'm going to close this issue for now. I spent a bit of time thinking about it, and I think the props are working as expected. If the explanation above didn't make sense, just let me know in this issue and we can reopen it and keep the discussion goin'!

> That ^^^ is just fantastic! Can we get the drawing as a PR added to the README?

Sure. I can whip something up sometime soon.

**Comment by arkist** [comment]
in the case of old plain infinite scroll,
I'm using a negative value on `bottomOffset` and it just works. 
(waypoint is placed on bottom of page, and scrollableAncestor is `window`)

offset behavior is hard to understand than the threshold. 😂

**Comment by xeophin** [comment]
I would agree that this illustration should be part of the documentation – I just spent a whole morning trying to figure out why topOffset and bottomOffset would not work the way I was expecting them to work, and only digging through closed issues brought me to this illustration – and, finally, enlightenment 😄

**Comment by jmeas** [comment]
Dropped the ball on this one! I started redoing the drawings to make them better, then I was like, "wait...I can make some updates to the website, too!" and started planning that, then got overwhelmed and 9 months passed.

I'll start small and add these to the README. This weekend – promise 🤞

**Comment by Ashok1602** [comment]
Currently i am using react-waypoint@9.0.1,
but onEnter is not working properly in windows operating system but it is fine in Ubuntu.
it it working only when screen resizing.
so plese give me any solution.
I used topOffset,bottomOffset,scrollableAncestor some properties like currentPosition,previousPosition also used.
