### ISSUE TITLE
Performance of componentDidMount

### ISSUE THREAD

**Issue by thomassuckow** [brigade/react-waypoint#110]
I am using react-waypoint to manage a large scroll region with varied size objects. For performance, I only keep a handful rendered at a time and when out of view `display:none`.

As objects come into view I place a waypoint after it so I know when to add another object. Unfortunately every time I add a waypoint I get hit with a ~9ms render penalty.

<img width="532" alt="screen shot 2016-07-13 at 8 21 22 am" src="https://cloud.githubusercontent.com/assets/3100037/16808833/f60c9712-48d2-11e6-9528-0b0b6841f02d.png">

In the more ideal case these items would be inspected after giving the browser a chance to render on its own. Unfortunately there is no onPaint event which only leaves setTimeout with its 4ms minimum delay.

I have created a experimental change at:
https://github.com/thomassuckow/react-waypoint/commit/5097201a1a3c557bcd5a61ab78b48d8aeeccc38b

It is a notable improvement to the jank but doesn't always result in no forced layout.

I am interested in feedback on this change.

**Comment by lencioni** [comment]
Thanks for digging into performance! I wonder if `requestIdleCallback` would make sense here.

**Comment by trotzig** [comment]
The recently added `throttleHandler` might be useful too. https://github.com/thomassuckow/react-waypoint#throttling

**Comment by thomassuckow** [comment]
That would help with the layout. I am trying to think of how we could abuse the throttleHandle to also capture the "ReacalculateStyle". Could make a function that the first time it is called does the onMount logic and every time thereafter does just the handleScroll logic.

**Comment by thomassuckow** [comment]
I'm going to have to shelve this for a while since what I have built "works". I'm hoping to come back to it in a month or two when we get to more of a performance phase of development.

**Comment by trotzig** [comment]
I'm closing this issue now. Feel free to reopen at will!
