### ISSUE TITLE
Hi, is the npm up to date?

### ISSUE THREAD

**Issue by wonilsuh** [brigade/react-waypoint#113]
Hi there, I'm noticing that `topOffset` and `bottomOffset` are not working when I install it from npm, but when clone this git and build, they work. So I was wondering if npm was out of date.

Thanks for this very nice package BTW!

**Comment by jmeas** [comment]
@wonilsuh I'm using the latest release from npm ([v3.1.0](https://github.com/brigade/react-waypoint/releases/tag/v3.1.0)), and the new props have been working for me. Are you sure you've installed a version >3.0.0?

**Comment by wonilsuh** [comment]
@jmeas For some reason 1.3.1 was installed. I re-installed from npm and It's working fine now. This is great. Thanks!!!!!!

**Comment by jmeas** [comment]
Awesome! Glad we got that figured out :v:
