### ISSUE TITLE
Function not binding to onEnter?

### ISSUE THREAD

**Issue by LucasKA** [brigade/react-waypoint#121]
Hi guys,

I'm trying to bind a function to `onEnter` inside an ES2015 Component Class, and when it renders I get `onEnter=onEnter()` in the react tools. Is there something I'm missing on the ES2015 front? Running the function in `componentDidMount` works, and with react VisibilitySensor, which seems like a less elegant solution than this.

<img width="466" alt="screenshot 2016-10-05 11 13 08" src="https://cloud.githubusercontent.com/assets/1824267/19125797/4bac5b10-8aed-11e6-99fb-c2016c361f55.png">

**Comment by LucasKA** [comment]
Here's the usage of it too.

```
  <Waypoint onEnter={this.injectAd(this.props)} >
        <div className="gallery-unit">
          <h5>advertisement</h5>
          <div id={this.props.divId} />
        </div>
      </Waypoint>);
```

**Comment by jmeas** [comment]
@LucasKA , silly question: is the return value of `injectAd` another function? It's being called at the time that the component is rendered, rather than `onEnter`.

If the answer is no, then I might expect the code to be...

`<Waypoint onEnter={this.injectAd.bind(this.props)} >`

Just want to make sure that's not a mistake :v:

**Comment by LucasKA** [comment]
@jmeas No, injectAd just runs the google dfp function that injects the iframe into that `{this.props.divId}` in the component there.

The ad shouldn't render unless the ad is in viewport, so componentDidMount is not enough. :(

**Comment by jmeas** [comment]
Ah okay, @LucasKA . That makes sense. In that case, if you switch the code to the little snippet that I wrote above, does it solve the issue?

**Comment by LucasKA** [comment]
@jmeas Nope. 😢 Binds in ES2015 are done in the constructor, my JSX linter complains if I do it in there.

If I put it in the code, it complains of my props no longer being defined.

**Comment by jmeas** [comment]
Well, specifics aside, something _like_ this should solve your issue. My thinking is that this seems to be analogous to the difference between:

1. `window.addEventListener('scroll', onScroll())`
2. `window.addEventListener('scroll', onScroll)`

Item 1 above is a mistake because the function is called *at the time that the event is registered*. In the same way, you're calling `this.injectAd` instead of registering it as the callback for `onEnter`.

My guess is that you need to rewrite your code to be more like item 2 above.

Does that make sense?

**Comment by LucasKA** [comment]
It does make sense. Can you show me how a console.log would be bound as the callback of onEnter in Waypoint? I figured it was something like that.

**Comment by LucasKA** [comment]
I ask because usually registering it as a callback is simple as `onEnter={ () => { console.log('wheee'); } }` when I'm having trouble with immediate calling.

**Comment by jmeas** [comment]
@LucasKA , the snippet you wrote, where you wrap it in another function, is one common approach I've seen. I've also seen using `fn.prototype.bind`, and `_.partial`. Code snippets for each of these:

```jsx
<Waypoint onEnter={() => { console.log('wheee'); }}/>
<Waypoint onEnter={console.log.bind(console, 'wheee')}/>
<Waypoint onEnter={_.partial(console.log, 'wheee')}/>
```

There might be other ways, too! Each of these will have the same functionality, though. Does this help at all?

**Comment by LucasKA** [comment]
@jmeas 

It does, however, I still couldn't get mine to trigger unless it returns explicitly, which is not usually the case when using a closure like that.

In ES2016 you can explicitly return the result with the () instead of curly braces.
`<Waypoint onEnter={() => (this.injectAd(this.props)) } />`

Which seems to get waypoints to work, but also strange because I still couldn't get a console log to trigger. 

Somedays you eat the bear, others, the bear, well he eats you.

**Comment by jmeas** [comment]
Ah, interesting. I'm afraid I'm not sure what the issue was with the console.log you were seeing, but I'm glad you were able to get it to do what you needed it to do!

Feel free to close this issue if you think it's been adequately resolved :v:

**Comment by trotzig** [comment]
Thanks for sorting this out. I think we're doing something funky when we call handler functions however. Look at this line: 
```jsx
  this.props.onEnter.call(this, callbackArg);
```
https://github.com/brigade/react-waypoint/blob/8c371c4aad000038341d2c2b8c3b4ecb73216b69/src/waypoint.jsx#L161

I don't see the reason why we would need to use `.call` here. We should just call the method directly and not worry about re-binding `this`. 

I'll push something soon.

**Comment by jmeas** [comment]
@LucasKA , I'm going to go ahead and close this issue, as it seems to me like you've been able to figure out a solution that works for you. If that's not the case, then no worries, just comment here and we can keep working together to figure it out.
