### ISSUE TITLE
Use passive event listeners by default

### ISSUE THREAD

**Issue by lencioni** [brigade/react-waypoint#122]
To maximize performance, I think it would be a good idea to use passive event listeners by default. If there are folks who want to cancel the scroll event, we could provide a prop to allow these to opt in to active event listeners, but my hunch is that isn't a likely use-case for waypoint.

More information: https://blog.chromium.org/2016/05/new-apis-to-help-developers-improve.html

**Comment by jmeas** [comment]
Sounds like a great idea to me.

Are you thinking of copy+pasting [the feature detection code from Modernizr](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/dom/passiveeventlisteners.js#L26-L35) into this lib, or do you think you'd want to add Modernizr as a dep/peerDep?

**Comment by lencioni** [comment]
If we can find something more modular than Modernizr, I think it would be good to use a dependency. Otherwise, I think copy+pasting from here https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection would be fine.
