### ISSUE TITLE
Uncaught TypeError: handlers[index] is not a function

### ISSUE THREAD

**Issue by PEM--** [brigade/react-waypoint#126]
This appeared when I've updated to `4.0.0`.
![capture d ecran 2016-10-20 a 09 42 00](https://cloud.githubusercontent.com/assets/227831/19550427/9d43e2be-96a9-11e6-9016-0ac04b3a5b45.png)

**Comment by trotzig** [comment]
Thanks for the report @PEM--, I'm looking into it. Can you share a little bit more about how you use react-waypoint? Are you for instance using `throttleHandler`?

**Comment by PEM--** [comment]
It's me that is thanking you for sharing this nice component.

I've used with and without the `throttleHandler`. Same problem in both cases. Recently, I've added the `fireOnRapidScroll`. Not sure if it's related.

**Comment by trotzig** [comment]
Probably not. I think this is caused by a race condition between handling a scroll/resize event and removing/unmounting a waypoint. I'm closing in on a fix.

**Comment by trotzig** [comment]
Okay, I think I found it. I have a solution in mind that I hope to push in a short while.

**Comment by PEM--** [comment]
👍

**Comment by trotzig** [comment]
I just pushed version `4.0.1` with a fix for this error. Again, thanks!

**Comment by PEM--** [comment]
It works like a charm 👍
