### ISSUE TITLE
Uses for `throttleHandler` prop

### ISSUE THREAD

**Issue by lencioni** [brigade/react-waypoint#129]
Related: #73, #98

In v4, we made some performance improvements to add fewer event listeners, and to also use passive event listeners. With these changes I'm wondering if the `throttleHandler` prop is still useful. In our codebase, I've witnessed folks using it even when it wasn't useful, so I am wondering if it adds more confusion and uncertainty about the performance characteristics of this component than it is worth. If it isn't useful, or if the same thing can be accomplished via composition, I would like to remove this prop from this component to simplify its API.

Can folks here who are using `throttleHandler` check out the performance characteristics of v4.0.2+ without the `throttleHandler` prop and please post a comment on this issue with what you've found? I'd really like to have a better understanding of how you are using this prop and what benefits you are seeing from its use.

**Comment by trotzig** [comment]
I'm in favor of removing it unless we can provide some numbers telling us it's actually useful. We're not using it ourselves despite some pages having 20-30 waypoints. 

@bySabi could you share how you're using this prop in your app(s)?

**Comment by bySabi** [comment]
I use throttle on apps that animated scroll to hash links.
User generated scroll events rarely will have any performance impact but programmatic generated events could degrade it mostly on mobile environments.
I´m in favor of remove it too but, IMO, we must wait until `passive events` goes mainstrem on major browsers and hardware constrained devices.
One thing to take in consideration is that `throtteHandler` prop actually not throttled anything is just a Doc convention. Maybe the prop name must be change in order of avoid any confusion but retain it like a `_handleScroll` bridge is useful in some cases, `throttling` will be one.

And finally I will like to say that I don´t like the current direction of React-waypoint. Latest addition: throttleHandler, debug, bottom/top offset, TargetEventHandler and for coming had become React-waypoint too bloated. Still think that this project must be split on a scroll metal/DOM/debug/performance part and a Pure React Component like I propose some times ago.

**Comment by trotzig** [comment]
Thanks for that bit of input @bySabi. It's interesting about the programmatically powered scroll. 

@lencioni: do you have any idea when passive scroll listeners might be implemented in other browsers? 

I agree about recent props adding a bit of bloat, so removing `throttleHandler` should be a good thing. The `debug` prop too shouldn't be necessary, though it has helped me out when responding to support requests a few times. The `bottomOffset` `topOffset` made the tool a lot more powerful. Those props are a little bit harder to use than the old `threshold`, but I can't think of a good way to simplify. 

I'm not too sure about the project split however. I've gone down that path before (diffux became diffux and diffux-core) and it made things harder overall to maintain.

**Comment by bySabi** [comment]
@trotzig deprecated `throttleHandler` in favor of a more generic _handleScroll "bridge?" API and update Doc will be enough.
Your are right that split it could make a little harder to maintain but is not more true the fact that React-waypoint cannot cover all scroll behaviours and at some point many developers will request them. 
Is a shame that this code cannot be reuse on related components. Myself copy paste a litte code to a WIP project [React scrollAware](https://github.com/bySabi/react-scrollaware) created with this idea.

**Comment by lencioni** [comment]
@trotzig it looks like [passive event listeners has landed in Safari nightly](https://bugs.webkit.org/show_bug.cgi?id=158601), so I imagine it will hit iPhones eventually. And it is already in Chrome, so Android users are all set. Folks using IE and Edge seem to be out of luck right now.

Regarding the `debug` prop, we could wrap it in statements like

```js
if (process.env.NODE_ENV !== 'production') {
  ...
}
```

which folks could configure their builds to strip for production.

**Comment by trotzig** [comment]
Closing this as we've now removed support for `throttleHandler`.

**Comment by jooj123** [comment]
The fact that IE 11 and Edge dont support this (and there is enough usage of these browsers) - isnt that a reason to leave throttle (or at least the option to throttle) in ?

Means performance will be poor for these browsers and for lots of use cases, we still need to support IE11 and Edge

**Comment by trotzig** [comment]
@jooj123 that's a good point. Are you noticing poor performance in these browsers right now? Before we add throttling back however, it would be good to do some profiling to make sure that we're solving the right thing. Would that be something you'd be willing to explore?

**Comment by bySabi** [comment]
I would not add a specific "throttling" API but a generic callback in order of  attach what ever behaviour is needed.
