### ISSUE TITLE
Set up 'global' style build.

### ISSUE THREAD

**Issue by flarnie** [brigade/react-waypoint#13]
We have set up a 'npm' style build system modeled after the 'React-Router' repository's 'npm' build. It would be nice to also have a 'global' style build. See the ['React-Router' package.json][react-router-package-json] and their 'build/global' directory.

Once we have a global build set up, we could use that for issue #14  (Using global build in 'gh-pages' branch.)

[react-router-package-json]: https://github.com/rackt/react-router/blob/master/package.json
[react-router-global-build]: https://github.com/rackt/react-router/tree/master/build/global

**Comment by tdooner** [comment]
Does "global style build" mean a version which isn't a CommonJS module?

I found myself wanting this a moment ago -- I'm rewriting Mosaic to be React this weekend, and replacing the jQuery lazy load with `react-waypoint`, but I'm not fancy enough for the CommonJS module stuff yet.

Anyway, removing the `var React = require('React')` and the `module.exports = Waypoint` worked, but it would be good to just be able to use the official bower/npm build.

**Comment by lencioni** [comment]
> Does "global style build" mean a version which isn't a CommonJS module?

Yes, exactly.

To be honest, I think you'd be best off just setting up webpack. They have [a pretty full-featured webpack react starter](https://github.com/webpack/react-starter) that should get you up and running pretty quickly.

**Comment by trotzig** [comment]
@flarnie is this still important? I'm trying to close out old and inactive issues, and this hasn't been touched in a while.

Also, hi! We miss you!

**Comment by trotzig** [comment]
Closing. Even though this would be convenient, I don't think we should support this use-case.
