### ISSUE TITLE
Allow add custom class in the `span` generated

### ISSUE THREAD

**Issue by obetomuniz** [brigade/react-waypoint#130]

**Comment by lencioni** [comment]
Hi @obetomuniz! Can you help me understand your use case?

**Comment by obetomuniz** [comment]
Hey @lencioni :D I need add a `position: absolute;` and `top: 0;` in the `<span />` generated because my container have a `padding-top: 58px;`.

<img width="293" alt="screen shot 2016-10-26 at 2 45 40 pm" src="https://cloud.githubusercontent.com/assets/1680157/19735571/e7d27cd8-9b8a-11e6-9f4b-3131892a903a.png">

**Comment by lencioni** [comment]
I see! Thanks for the additional context. That is very helpful.

Does it work to wrap it in a containing element with those styles on it? It is generally best to avoid passing CSS classes between components. https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785

**Comment by obetomuniz** [comment]
I agree with you! Make sense to reduce complexity.
