### ISSUE TITLE
two separate waypoint components firing simultaneously

### ISSUE THREAD

**Issue by MarcZenn** [brigade/react-waypoint#133]
Sorry if my question is relatively novice level but I'm very new to React and React Waypoints. Currently I'm running into an issue where I have two waypoint components, each within its own container element, and as soon as I land on the page both the uppermost waypoint and the waypoint immediately after are both firing despite not scrolling to the second waypoint. Here is an example of my code. 

```
//import react
import React, {Component} from 'react';

// Components
import Nav from '.././Partials/Nav.jsx';
import {Col, Row, Grid} from 'react-bootstrap/lib';
import Waypoint from 'react-waypoint';
import {Link} from 'react-router';


class ProfessionalContributions extends Component {
  constructor(props) {
    // super simply allows us to call methods defined on any parent Components of this Component
    super(props);
    this.state = {
     entered: false
    };
  }

  componentDidMount(e) {
    setTimeout(function() {
      this.setWaypoint(true, 1);
    }.bind(this), 10);
  }

  setWaypoint(bool, int) {
    console.log(int);
    // Set waypoint state
    if (!bool) {
      this.setState({ entered: false});
    } else {
      this.setState({entered: true});
    }

    // Use updated state for UI waypoints animation.
    if(!this.state.entered) {
      document.getElementById('wp-dot-' + int).className = 'empty';
    } else {
      document.getElementById('wp-dot-' + int).className = 'filled';
    }
  }

  render(){
    return(
      <section>
        <Nav />
        <div className="professional-contributions-content">
          <Row className="work-item professional-contributions-header">
            <Col xs={12} className="text-left">
              <Waypoint
                onEnter={this.setWaypoint.bind(this, true, 1)}
                onLeave={this.setWaypoint.bind(this, false, 1)}
              />
              <h1>This page represents a collective body of work built during my employment as a full-time developer within an organization, startup or agency. Feel free to peruse the projects and contact me if you have any questions, concerns or skeptical inquiries.</h1>
            </Col>
            <Col xs={12}>
              <ul>
                <li>
                  <i className="devicon-angularjs-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-bootstrap-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-css3-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-d3js-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-git-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-gitlab-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-gulp-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-heroku-original colored"></i>
                </li>
                <li>
                  <i className="devicon-javascript-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-laravel-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-less-plain-wordmark colored"></i>
                </li>
                <li>
                  <i className="devicon-linux-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-mongodb-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-mysql-plain colored"></i>
                </li>
                <li>
                  <i className="devicon-nodejs-plain colored"></i>
                </li>
              </ul>
            </Col>
          </Row>

          <Row className="work-item kickfurther">
            <Col className="text-left" xs={12} md={6}>
              <Waypoint
                debug={true}
                onEnter={this.setWaypoint.bind(this, true, 2)}
                onLeave={this.setWaypoint.bind(this, false, 2)}
              />
              <h2>A Thing Called Kickfurther</h2>
              <p>The Micro-Retail Revolution.</p>
            </Col>
            <Col xs={12} md={6}>
              <img src="/public/images/kf-example_image.png" />
            </Col>
          </Row>




          <div className="scroll-tracker">
            <div className="filled" id="wp-dot-1"></div>
            <div className="empty" id="wp-dot-2"></div>
            <div className="empty" id="wp-dot-3"></div>
          </div>
        </div>
      </section>
    )
  }
}




ProfessionalContributions.propTypes = {
  // .....
}



export default ProfessionalContributions

```

**Comment by trotzig** [comment]
Hi @MarcZenn, I'm glad you're getting into react and react-waypoint! 

Just to make sure I understand this correctly: you expect the first waypoint to fire `onEnter` on page load, and the second waypoint to fire `onEnter` after scrolling down (to bring it into the viewport)? 

If that's ^^ the case, then the most common issue is that there's something above the waypoint that's lazy-loading, so that it doesn't have a height initially and then suddenly it has. I don't see any obvious suspects for that in your code however, but it depends a little on how your `devicon-` styles behave. Could it be that the CSS for those classes are lazy-loading?

**Comment by MarcZenn** [comment]
Hey trotzig thanks for the tip! It sounded like that actually might've been the culprit but once I removed the devicons I still am seeing the same behavior. To clarify, the expected behavior is that upon landing on the page only the first waypoint onEnter event fires while the the other waypoint further on down the page remains inactive until  it is scrolled to and its onEnter event fires. Instead what I'm seeing is that both waypoint onEnter events fire immediately upon landing on the page (the first waypoint onEnter fires and then immediately afterwards the second waypoint onEnter fires further down the page without having to scroll to it).

**Comment by trotzig** [comment]
Is there a publicly accessible url where I can test this? Or perhaps you can provide a minimal(ish) repro case somewhere?

**Comment by jmeas** [comment]
> To clarify, the expected behavior is that upon landing on the page only the first waypoint onEnter event fires while the the other waypoint further on down the page remains inactive until it is scrolled to and its onEnter event fires.

Just to clarify, is the other waypoint further down on the page is _offscreen_? If both are unscreen, then I would expect both to fire. This is probably not the issue, but I figured I'd mention it just to be explicit that multiple waypoints will fire if they're all on screen at once.

If this isn't the issue, then no worries. I think a demo somewhere, like @trotzig mentioned above, might be the best way for us to help ya troubleshoot this :v:

Sorry for the trouble, @MarcZenn !

**Comment by MarcZenn** [comment]
Hey no worries at all! 

Currently you can view my project here http://marczenn.com and the specific page where I'm encountering the issue here: http://marczenn.com/#/professional-contributions

I have another Component in this project that uses waypoints nearly exactly the same way and that page works just fine. Here's the link to that: http://marczenn.com/#/works

I'm using a free heroku Dyno so if the page takes awhile to render it's because my heroku server is booting back up :/ (figured I'll pay up once my project is nearer to completion). 

Thanks again guys for all the help on this!

**Comment by jmeas** [comment]
Thanks for the links!

@trotzig (and anyone else interested) , here's [a commit](https://github.com/MarcZenn/MarcZennPersonalWebsite/commit/e0856fd37d0df13183a620aa4d7767df20c0fcf8) that can help identify the location of this lib's usage within the source code.

I'll dig around myself to see what I can find when I've got some time ✌️

**Comment by trotzig** [comment]
Thanks for the links @jmeas and @MarcZenn. I've been (and still am) afk. I'll have a look when I'm back at it.

**Comment by trotzig** [comment]
After looking at your site, I have a few theories. One is how your CSS is applied. It seems you are using the `style-loader` webpack loader. It's possible that styles are injected after the DOM has been updated, which would lead to waypoints being mispositioned on initial render. I don't have enough experience with that loader though to know if this could be the case. Another theory is that font loading is somehow interfering. It looks like the body is rendered invisible at first, and made visible when fonts are available. I don't actually know how element positioning would work in this scenario. Both of the theories would explain why the `/works` page works, because that page has a splash screen that will stay long enough for both fonts and css to be applied before the real content is shown. 

I hope you're able to track this down, and I'm interested to hear what you find out. There's probably something here that others could benefit from.

**Comment by trotzig** [comment]
I'm still interested to hear if you were able to find anything @MarcZenn! In the meantime, I'm going to close out this issue.
