### ISSUE TITLE
Use 'global' waypoint build in 'gh-pages' branch

### ISSUE THREAD

**Issue by flarnie** [brigade/react-waypoint#14]
Right now on our [Github Pages branch][gh-pages-branch] we have an old version of React-Waypoint that is tweaked to work with our inline JS for the examples. Instead, let's use the global build.

Solving this issues blocked on setting up the global build, which is issue #13.

[gh-pages-branch]: https://github.com/brigade/react-waypoint/tree/gh-pages

**Comment by trotzig** [comment]
@flarnie is this still important? I'm trying to close out old and inactive issues, and this hasn't been touched in a while.

Also, hi! We miss you!

**Comment by trotzig** [comment]
Closing due to lack of response.
