### ISSUE TITLE
infinite requests if content height is lower than window height

### ISSUE THREAD

**Issue by optimatex** [brigade/react-waypoint#140]
In my use case content could be 3 tiny thumbnails for example. If that is true waypoint will execute callback none stop. How can i avoid none stop calling? i saw similar issues but have no idea how to use those solutions in my case.
thanks!

**Comment by jmeas** [comment]
@optimatex can you provide a bit more detail? Is there a repo somewhere, or could you post some example code?

**Comment by optimatex** [comment]
Sure
here is my infinite list components
```
'use strict';
@observer
class NotionsList extends Component {
   render() {
      const { internal } = this.props;
      const { collection, load_complete, preventUpdate } = this.props.store;
      const define_list = () => {
         if (load_complete && collection.length < 1) {
            return (
               <Empty_List>
                  No one Notion
               </Empty_List>
            )
         }
         else if (collection.length > 0) {
            return render_list
         }
      }
      const render_list = collection.map((model, index) => {
         return <Notion_Layout internal={internal} store={model} key={index} />
      });
      const define_animation = () => {
         if (load_complete === false) {
            return <Loading_Animation class='for_block' />
         }
      }
      const define_infinity = () => {
         if (this.props.infinity && preventUpdate === false && load_complete === true) {
            return <Waypoint
               key={'1'}
               onEnter={this._request_more.bind(this)}
               onPositionChange={this._handlePositionChange.bind(this)} />
         }
      }

      return (
         <ul className="notion__list">
            { define_list() }
            { define_animation() }
            { define_infinity() }
            { this.props.children }
         </ul>
      )
   }
   constructor(props) {
      super(props);
      this.state = {
         scrollCompleted: 1
      }
   }
   _request_more(event) {
      this.props.store.update(this.state.scrollCompleted);
      this.setState({ scrollCompleted: ++this.state.scrollCompleted });
   }
} 
```
and here is a style of each image and a style of list container
```
.visual__cover{
   display: inline-block;
   float: left;
   position: relative;
   list-style-type: none;
   margin-bottom: -3px;
   margin-right: -3px;
   width: 33.33%;
   height: 170px;
   box-sizing: border-box;
   cursor: pointer;
   border: 3px solid $border__color_base;
   background: $background_accent;
   background-position: center;
   background-size: cover;
}

.notion__list{
   margin: 0;
   padding: 0;
}
```
maybe i have to add some more details? currently i have no idea which one

**Comment by trotzig** [comment]
Could it be that the waypoint is unmounted and then remounted as a result of this conditional evaluating to false: `this.props.infinity && preventUpdate === false && load_complete === true`? In general, it should be safe to keep the waypoint mounted until you know you don't have any more items to load.

**Comment by optimatex** [comment]
@trotzig  thanks for advice. I would like to do this. I can move this condition into callback execution

```
_request_more(event) {
   if (preventUpdate === false && load_complete === true) {
      this.props.store.update(this.state.scrollCompleted);
      this.setState({ scrollCompleted: ++this.state.scrollCompleted });
   }   
}
```

in this implementation client will not bother server with redundance requests (if previous request is in process or if there are no more items in database). 
But what about additional load to browser? i mean if this component's method ` _request_more(event)` will be executed >50 times per min it could overwhelm brower. How do u think?

**Comment by trotzig** [comment]
That shouldn't be a problem, though I still suggest you try to figure out why the waypoint keeps remounting. Assuming that's the issue for the infinite triggering.

**Comment by optimatex** [comment]
i'm sorry for a long response. I changed my realization and always render waypoint. If requesting is in progress i don't execute callback (like i mentioned in my previous comment). Thank u for nice support!

**Comment by trotzig** [comment]
Glad you were able to get things resolved! Thanks for being patient and for continuing to use react-waypoint!
