### ISSUE TITLE
onEnter never fires

### ISSUE THREAD

**Issue by stanleycyang** [brigade/react-waypoint#158]
Here is my code

```js
  renderBlocks = () => {
    const {
      items
    } = this.props;

    if (items.length) {
      return <section>
        {(() => {
          return items.map((item, index) => {
            return <Block testimonial={ item } key={ index } />
          });
        })()}
      </section>
    } else {
      return <NoPost />
    }
  };

  renderWaypoint = () => {
    return <Waypoint
        onEnter={ this.loadBlocks }>
          <span>Loading..</span>
        </Waypoint>
  }

  loadBlocks = () => {
    console.log('loading more!');
  }

  render() {
    return (
      <section>

        <div>
          { this.renderBlocks() }
        </div>

        <div className='waypoint'>
          { this.renderWaypoint() }
        </div>

      </section>
    )
  }
```

However, the `Waypoint` only gets fired once and never again (even when scrolled upon). What could be the issue that is preventing the `Waypoint` from working?

**Comment by trotzig** [comment]
It's hard to say without more information. Do you have a publicly available example where I can check? If not, adding the `debug` prop to the waypoint might help understanding what's going on.

**Comment by jmeas** [comment]
@stanleycyang , my guess is that this is the same problem as described in #155. tl;dr if your Waypoint is in view when the page loads, then `onEnter` will not be called.

If this is correct, then adding the following:

```js
componentWillMount() {
  this.loadBlock();
}
```

should fix the issue.

**Comment by stanleycyang** [comment]
I switched modules to [this](https://github.com/joshwnj/react-visibility-sensor) with the same example and it worked. I don't get why `Waypoint` wouldn't do the same though.

@trotzig No I don't have a public example of it. I can try and put one together though

**Comment by jmeas** [comment]
@stanleycyang I'm very interested to see an example if you have time! It could help us fix what may be a bug with this library.

**Comment by stanleycyang** [comment]
So examining my code more, I believe it's because I'm using the [react-sidebar](https://github.com/balloob/react-sidebar/) module, which has this issue: https://github.com/balloob/react-sidebar/issues/77.

Sorry about the issue!

**Comment by jmeas** [comment]
@stanleycyang , no need to apologize. That's pretty interesting, but a real pain! Thanks for taking the time to follow up here. I hope you're able to get things working as expected.
