### ISSUE TITLE
Any way to reference a specific waypoint in the onEnter/onLeave handler?

### ISSUE THREAD

**Issue by andremalkine** [brigade/react-waypoint#160]
I have a series of waypoints marking important boundaries on a long, scrolling page. I'd like them all to fire the same onEnter/onLeave handler rather than writing individual handlers for each Waypoint. Would it be possible to pass the `key` attribute or the `id` of the waypoint itself as part of the data object these handlers receive?

**Comment by jmeas** [comment]
Hi @andremalkine ! Thanks for the issue.

> Would it be possible to pass the `key` attribute or the `id` of the waypoint itself as part of the data object these handlers receive?

Yup, doing something like this is technically possible from within the lib. It would require updating [these lines](https://github.com/brigade/react-waypoint/blob/66939d3ff4b83a33441846dd478c17ee2160ae8e/src/waypoint.jsx#L301-L309) to be something like:

```js
const callbackArg = {
  currentPosition,
  previousPosition,
  event,
  waypointTop: bounds.waypointTop,
  waypointBottom: bounds.waypointBottom,
  viewportTop: bounds.viewportTop,
  viewportBottom: bounds.viewportBottom,
  id: this.props.id // or whatever
};
```

Although I understand the need, I'm not sure if I'm convinced that we need it. Would a system like one of these work for you instead, @andremalkine ?

```js
// If it's a long list of items...
render() {
  return (
    <div>
      {myThings.map((thing, index) => (
        <Waypoint
          key={index}
          onEnter={this.onWaypointEnter.bind(this, index)}/>
      ))}
    </div>
  );
}
```

```js
// If it's a list of items with some sort of identifier
render() {
  return (
    <div>
      {myThings.map((thing, index) => (
        <Waypoint
          key={index}
          onEnter={(waypointData => this.onWaypointEnter(thing.id, waypointData))}/>
      ))}
    </div>
  );
}
```

**Comment by trotzig** [comment]
I'm assuming you want to avoid creating dynamic functions? That sounds like a valid concern. I think it might make sense to allow an identifier prop to be passed in, with the sole purpose of making it easier to write reusable `onEnter/onLeave` handlers. 

Another option would be to allow an arbitrary `metadata` prop to be passed in, which will then get passed to handlers untouched. 

Yet another option would be to simply send back the DOM element that we use internally for the waypoint. With the new support for `children`, you could prepare a custom DOM element with some metadata/attributes that you can then use in the handler. 

Just brainstorming, I'd be interested to hear other people's thought.

**Comment by andremalkine** [comment]
@trotzig  That is correct, this comes from a desire not to write anonymous functions in-line. I think any of the suggestions you made would be great.

That being said, using bind or otherwise works fine if you don't mind writing that way.

**Comment by trotzig** [comment]
`bind` will work, but [you still end up creating new functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind).

**Comment by jmeas** [comment]
> I'm assuming you want to avoid creating dynamic functions? That sounds like a valid concern.

:+1: 

> Another option would be to allow an arbitrary metadata prop to be passed in, which will then get passed to handlers untouched.

I like this option :+1: .

**Comment by trotzig** [comment]
May I ask how many waypoints you use on a page @andremalkine? I would expect scrolling lag to be the first performance issue you'd see if a page was flooded with waypoints, long before dynamic method creation would be a problem. I've been thinking about the use-case some more, and I don't see this as being unique to react-waypoint in any way. Basically any component that anonymously calls (not sending any data than can be used to identify the instance) has this problem. 

For instance, we have a `Button` component that takes an `onClick` function. No data is passed to the `onClick` handler, so on pages where we're dynamically rendering many buttons we have to create anonymous functions. I don't think it's the responsibility of the `Button` component or the waypoint to handle identifying itself.

I'm interested to hear what others think though. Also, are there techniques (or even npm modules) that can help with avoiding to create anonymous functions on each (re-)render? A simple memoization might be enough: 

```
const handlers = {};

function memoizedHandler(id) {
  if (handlers[id]) {
    return handlers[id];
  }
  handlers[id] = () => {
    // do something useful with `id` here...
  };
  return handlers[id];
}

function MyComponent() {
  return (
    <div>
      {someList.map(({ id }) => (
        <Waypoint onEnter={memoizedHandler(id)} />
      )}
    </div>
  );
}
...
```

**Comment by andremalkine** [comment]
@trotzig I have a page with 5 viewport filling "sections". As the user scrolls, I'm interested in knowing when each new section enters and leaves the viewport. There is an arbitrary amount of content above them, and they can each overflow the viewport and be different heights if needed, so having waypoints is very handy/convenient.

I think the real motivation behind my question was the fact that each enter/leave triggers a very simple, similar action of declaring which section you're "in", 0-4. That's it. Writing that simple behavior over and over just felt odd, and I always try to spawn anonymous functions when rendering.

I like your memoization suggestion, it's a nice compromise between the two. You may still wind up writing a series of separate but nearly identical functions, but you avoid the aforementioned spawning.

**Comment by trotzig** [comment]
Thanks for the follow-up @andremalkine! I'm going to close this issue without any actions, as I think we've figured out a good-enough workaround for you and others who might run into the same issue.
