### ISSUE TITLE
topOffset not working

### ISSUE THREAD

**Issue by mschipperheyn** [brigade/react-waypoint#165]
I'm trying to trigger `onEnter` at a certain distance from the top but they trigger on the "edge" each and every time.

I've tried topOffset="15%" topOffset={50} etc. 

The waypoint containing div has position: relative and that div's container has this.

    position: absolute;
    perspective: 300px;
    width: 100%;
    height: 100%;
    overflow-x: hidden;
    overflow-y: auto

I have a page that is divided in "slides" and the next slide is already slightly visible by making each slide have a height of `98vh`. Unfortunately, this triggers the waypoint for the next slide automatically, which is what I'm trying to avoid by using `topOffset`. 

Here's some of the debug output with a `topOffset` of 15%.

	["waypoint top", 0]
	["waypoint bottom", 328.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "inside"]
	["previousPosition", "inside"]
	["waypoint top", 328.453125]
	["waypoint bottom", 1234.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]
	["waypoint top", 1234.453125]
	["waypoint bottom", 1764.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]
	["waypoint top", 1764.453125]
	["waypoint bottom", 2449.03125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]

and without a topOffset

	["waypoint top", 0]
	["waypoint bottom", 328.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "inside"]
	["previousPosition", "inside"]
	["waypoint top", 328.453125]
	["waypoint bottom", 1234.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]
	["waypoint top", 1234.453125]
	["waypoint bottom", 1764.453125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]
	["waypoint top", 1764.453125]
	["waypoint bottom", 2287.03125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]
	["waypoint top", 2287.03125]
	["waypoint bottom", 2529.03125]
	["scrollableAncestor height", 242]
	["scrollableAncestor scrollTop", 0]
	["currentPosition", "below"]
	["previousPosition", undefined]

**Comment by jmeas** [comment]
Hey there @mschipperheyn ! Sorry for the trouble, but i'm happy to help ya figure this out. What version of React and React Waypoint are you using?

Also, do you have code on GitHub for this use case, or you can make a short gist?

Based on your description of the problem, I would expect this use case to involve using "bottomOffset", since items scroll into view from the bottom of the page, and not the top. If this is the case, then your use of topOffset would affect when the onLeave handler is called.

Let me know if that helps! If not, provide some more info and we dig more into it.

**Comment by mschipperheyn** [comment]
I'm using react 15.4.2 and waypoint 5.1.0. You're suggestion of using bottomOffset looks promising. I will play around a little bit to see if this resolves it.

**Comment by jmeas** [comment]
Hey there @mschipperheyn , did you end up having time to see if `bottomOffset` does the trick?

**Comment by jmeas** [comment]
After reviewing this issue, I'm pretty confident the problem was using `topOffset` when `bottomOffset` was required instead. I'm going to close this out.

@mschipperheyn if you're still seeing issues, just comment here, and we can reopen this issue. I'd be happy to help you figure it out.

**Comment by pdfabbro** [comment]
I can't seem to get topOffset or bottomOffset working no matter what I try.  I'm using an old version (1.1.2).  Could that be the problem?  When were these props introduced?

**Comment by jmeas** [comment]
@pdfabbro, we have a changelog of all changes here:

https://github.com/brigade/react-waypoint/blob/master/CHANGELOG.md

Those props were introduced in v3.

**Comment by francisyip** [comment]
Top offset does not work for mw too.

**Comment by jmeas** [comment]
@francisyip ,we'll need more info to help you. Answers to these questions could help us:

1. What version of this library are you using?
2. What code are you trying to run?
3. What behavior are you observing?
4. What behavior would you expect to observe?

Provide that and we'll be happy to help out!

**Comment by ChrisCinelli** [comment]
Check this out: https://codesandbox.io/s/qxyRGMlp3

**Comment by ChrisCinelli** [comment]
Nevermind. I did not understand what `topOffset` is. The name is a little confusing.
What I wanted to do is doable with a  negative `bottomOffset`.

**Comment by pdfabbro** [comment]
They are both VERY confusing.  I still don't understand them, I just play with the numbers until it gives me what I want lol

**Comment by ChrisCinelli** [comment]
It is clear to me now. The offset are relative to the scrolling container and a positive offset means toward the center of the container. But it was obviously not what I was intuitively expecting.

**Comment by jmeas** [comment]
If either of you have a better naming scheme that you think could help newcomers, or if you can think of a simpler system that has the same function, we're always open to suggestions!

If you intend to use these props, though, I _strongly_ recommend you thoroughly read the documentation in [the README](https://github.com/brigade/react-waypoint#offsets-and-boundaries). It explains behaviors such as positive offsets pointing in, and negative offsets pointing out.

**Comment by pdfabbro** [comment]
I've read it before, looked at all the diagrams etc and still don't get it.  To me if I have a waypoint underneath something that is 50px high (for example), and I set the topOffset to 50px, it should kick in as soon as the top of my element is at the top of its container

**Comment by jmeas** [comment]
> I've read it before, looked at all the diagrams etc and still don't get it.

I'm sorry to hear that! I'd love to do whatever I can to help it make more sense to you.

> To me if I have a waypoint underneath something that is 50px high (for example), and I set the topOffset to 50px, it should kick in as soon as the top of my element is at the top of its container

I must not be following, because my interpretation of this is that this describes how the system works right now. Since positive values push the offsets in, a 50px high header leads to a value of `"50px"` for `topOffset`. From the docs:

> For instance, if your app has a 50px fixed header, then you may want to specify topOffset='50px', so that the onEnter callback is called when waypoints scroll into view from beneath the header.

Am I misinterpreting what you're saying?

**Comment by pdfabbro** [comment]
Funny I just random.ly chose 50.  Didn't realize that was the example in the doc.  So right now my header is 85 px.  I have an element that is about 70px height.  I am finding that I need to set topoffset to be 85 plus the height of my element in order for it to enter the waypoint when I want it to.

**Comment by jmeas** [comment]
@pdfabbro are you using the Waypoint in the following way:

1. No children (`<Waypoint {...props}/>`)
2. It is placed at the top of your element

?

If so, you might be able to solve your problem by placing the waypoint at the bottom of the content, or, by using children.

**Comment by pdfabbro** [comment]
I have no children and am placing it at the bottom of the element.

**Comment by developer239** [comment]
@jamesplease Why is bottom offset working on top offset doesn't? If I set `topOffset='100px'` waypoint always fires immediately when the element gets into view. If I use `bottomOffset=100px` it works as expected and the waypoint is "shifted" down by 100 pixels.

edit: It seems that bottom is used for entering and top is used for leaving.
