### ISSUE TITLE
[Help] Inside or above ok but never below

### ISSUE THREAD

**Issue by kud** [brigade/react-waypoint#170]
Do you have any idea why my waypoint returns be always inside or above but never below?

**Comment by kud** [comment]
<img width="75" alt="image" src="https://cloud.githubusercontent.com/assets/655838/24617775/3663fa70-1895-11e7-85e2-d0bf683a54cf.png">

```javascript
<hr />
        <Waypoint
          onEnter={this.handleNavEnter}
          onLeave={this.handleNavLeave}
          scrollableAncestor={window}
          debug={true}
        />
        <div
          className={styles.content}
          ref={(node) => { this.mainLayoutContainer = node }
        }>
```

**Comment by trotzig** [comment]
Judging by that example it looks like the waypoint will never be below the bottom edge of the screen. `below` is when the distance to the top of the screen from the waypoint is greater than the size of the containet. I could be missing something though, perhaps you can provide a little more context?

**Comment by jmeas** [comment]
@kud , were @trotzig 's suggestions helpful? If you're still having the issue, let us know and we can help further.

**Comment by kud** [comment]
Yes, I did something like this.

```javascript
<Waypoint
          onEnter={this.handleWaypointEnter}
          fireOnRapidScroll={false}
          scrollableAncestor={window}
          bottomOffset='95%'
        >
```

Thanks.

**Comment by jmeas** [comment]
Awesome! Glad you figured it out 👌
