### ISSUE TITLE
Breaking peer dependency change in minor version

### ISSUE THREAD

**Issue by JemarJones** [brigade/react-waypoint#174]
In https://github.com/brigade/react-waypoint/commit/836c24e3818f490aa2ebecf491cb9840f627918e a peer dependency on `"prop-types": "^15.0.0"` was added and this change made its way into `5.3.0`. This is a breaking change and causes the following error to be thrown `Uncaught Error: Cannot find module "prop-types"`.

**Comment by Deliaz** [comment]
Met the same issue. 
`yarn add prop-types` did fix for me, but it is temporary

**Comment by JemarJones** [comment]
@Deliaz Yeup that does fix the issue for anyone experiencing it, but this definitely should have been a major version bump.

**Comment by jmeas** [comment]
Whoops, we didn't catch this in review. @trotzig / @lencioni what do you two want to do? I'm conservative about breaking changes, so I'd bug fix-release this change away, then release it again as a major.

**Comment by lencioni** [comment]
That sounds good to me. I won't have time to work on this today though. @jmeas I gave you publishing access for the package if you want to sort this out.

Are there any other breaking changes we want to bundle with this?

**Comment by jmeas** [comment]
> @jmeas I gave you publishing access for the package if you want to sort this out.

Sure, I'll PR an update shortly, then cut a release once it's merged in.

> Are there any other breaking changes we want to bundle with this?

I can't think of any off of the top of my head.

**Comment by trotzig** [comment]
Sorry folks, this was my bad. I agree that we should push a patch release with a quick-fix, then another major release bringing it back.  

Thanks for making us aware of the issue @JemarJones, and thanks @jmeas for taking quick action.

**Comment by jmeas** [comment]
@JemarJones / @Deliaz , this has been published as v5.3.1. We'll follow up with v6.0.0 momentarily with this breaking change re-introduced.

Sorry again for the trouble! 🙈

**Comment by JemarJones** [comment]
@jmeas Thanks for the super quick response time on resolving this! Awesome component btw 🙂.

**Comment by jmeas** [comment]
> @jmeas Thanks for the super quick response time on resolving this! Awesome component btw 🙂.

:v: Glad it's working well for you! I like it, too!

As a follow-up to the bug fix release, [v6.0.0](https://github.com/brigade/react-waypoint/releases/tag/v6.0.0) was just released, and it adds back in the peerDep. Everything should be A-OK now.
