### ISSUE TITLE
v6.0.0+: Restrict React 0.14 versions?

### ISSUE THREAD

**Issue by jmeas** [brigade/react-waypoint#179]
I haven't tested this, but this tweet, https://twitter.com/dan_abramov/status/852193956322521089 had me thinking that we may need to restrict the React 0.14 support post-v6, given that we've begun using `prop-types` in that version.

**Comment by lencioni** [comment]
That sounds good to me. We probably also want to move prop-types to be a regular dependency instead of peerDependency/devDependency since it holds no state and doesn't need to be a singleton.

**Comment by trotzig** [comment]
> doesn't need to be a singleton
Can you explain this a little? :)

The risk we end up with if we move it to a regular dependency is that people end up with two instances of the dependency. Let's say we depend on `^15.0.0` and v 16 comes out. Then react-waypoint would continue using v 15, while the rest of the project has moved to v 16. And they end up with duplicate versions of prop-types.

**Comment by lencioni** [comment]
That should be fine though.

**Comment by jmeas** [comment]
I think we could go either way here.

For folks that don't use `prop-types`, having it in `peerDependencies` could stink for them. They need to install it in their project. And if Waypoint is the only lib that specifies it as a peerDep, then they might be annoyed at Waypoint. Having it as a `dependency` makes it more seamless for those people.

On the other hand, people who want the most control over their bundle would probably prefer we specify it as a `peerDependency` to ensure that they don't get dupes. I understand that the `prop-types` lib is small, but users may not be convinced that it's small enough to allow for a duplicate copy in their bundle. Although, perhaps there's some fancy webpack configuration they could use to zap the import statement completely.

A very, very quick glance at other libs suggests the community might be going for the ease-of-installation+dupes-dont-matter approach:

- [React Router](https://github.com/ReactTraining/react-router/blob/ed6f3de4ea8baf950e65fd35e6785e0b493fb9e6/packages/react-router/package.json#L44)
- [Redux-form](https://github.com/erikras/redux-form/blob/master/package.json#L64)

If we do keep it in peerDeps, we should add it (and the other peerDeps) to the README. Right now, the installation instructions _technically_ won't get folks up and running.
