### ISSUE TITLE
Efficient Solution For Waypoint Child In Full View?

### ISSUE THREAD

**Issue by jabacchetta** [brigade/react-waypoint#180]
What is the most efficient solution for ensuring that a waypoint child with dynamic height is in full view when scrolling that content into view from the bottom?

Currently I'm just estimating by using `bottomOffset="100px"`.

My initial thought is to just use the `onPositionChange` prop along with `getBoundingClientRect()` to do a manual calculation?

**Comment by jmeas** [comment]
I'd just put a regular Waypoint (no children) at the bottom of the content.

**Comment by jabacchetta** [comment]
Wow, I tried to make that way more complicated than it needed to be — completely misunderstood the concept of the waypoint.

Thank you!

**Comment by jmeas** [comment]
:v: I'll close this out, then. If you still have problems, just comment here and we can reopen this.
