### ISSUE TITLE
onLeave event never been fired

### ISSUE THREAD

**Issue by optimatex** [brigade/react-waypoint#181]
Hi. Previously, my react-waypoint implementation works perfect. Right now i have some strange issue - sometimes it works, but sometimes it doesn't. I hooked onEnter, onLeave, onPositionChange handlers to log what is goin on and turned on debug mode. 
Here what i get when react-waypoint doesn't work at all
![localhost_3198_kit_base_objects-popular - google chrome 2017-04-18 17 08 02](https://cloud.githubusercontent.com/assets/8351201/25135000/b5b8f2b0-2459-11e7-8ff7-022f4831adcb.png)
As u can see, onLeave event doen't triggers. 
And here is log from working case
![localhost_3198_kit_base_objects-popular - google chrome 2017-04-18 16 51 25](https://cloud.githubusercontent.com/assets/8351201/25135049/dff5b112-2459-11e7-8f4e-9c2c21603235.png)

What can it be? thanks

**Comment by trotzig** [comment]
We might need a little more context, but on a surface level, it looks like we picked up different `scrollableAncestor`s in between the two examples. Try adding `scrollableAncestor={window}` and see if that makes any difference. 

I'm going to keep this open even if that fix helps. It seems like we shouldn't ever use `body` as the `scrollableAncestor`. Can you check to see what css styles are attached to the `<body>` element? I want to understand what can cause this.

**Comment by optimatex** [comment]
Wow! That's helped me. Thanks for rapid answer and solution!
About styles: here is a screenshot
![localhost_3198_kit_base_objects-popular - google chrome 2017-04-18 17 41 44](https://cloud.githubusercontent.com/assets/8351201/25136671/50eea596-245e-11e7-854d-1d50d5295edc.png)

**Comment by trotzig** [comment]
Interesting, do you know why `overflow-x: hidden` is there? Not that this should matter, I'm just curious.

**Comment by optimatex** [comment]
sure. Website should has adaptation to mobile devices. When user clicks on menu, all content will shift right to expose sidebar. Like that 
![gistair com_kit_base_objects-popular - google chrome 2017-04-18 17 58 57](https://cloud.githubusercontent.com/assets/8351201/25137590/e61af280-2460-11e7-85dd-40a1e67fc94d.png)
If i will disable `overflow-x: hidden` horisontal scroll will appears (gray band on the bottom)

**Comment by trotzig** [comment]
I see, thanks for the info. And nice looking website by the way!

**Comment by optimatex** [comment]
Thanks

**Comment by jmeas** [comment]
Sounds like this has been figured out, so I'm going to close this issue. @optimatex , feel free to leave a comment here if this issue pops up again, and we can reopen it and keep the conversation going.

Cool site, by the way!

:v:
