### ISSUE TITLE
Add scrollableAncestor to debug output.

### ISSUE THREAD

**Issue by marlonpp** [brigade/react-waypoint#182]
I came across this weird behavior where if when the entry point of my application is the page where I have Waypoints it works fine, but, if the entry point is a different page that leads to a page where the Waypoints are, it doesn't.
What fixed the issue was ```scrollableAncestor={window}```, but it took me some time to figure out that because there is no log output for scrollableAncestor.

Would be great to have this info as part of the debug output.

**Comment by trotzig** [comment]
I think this is a good idea. I've seen this come up in the past as well (https://github.com/brigade/react-waypoint/issues/171 comes to mind). Would you be willing to make that change?

**Comment by marlonpp** [comment]
My bad, this already exists.
https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L49

Only thing that could change is, removing `process.env.NODE_ENV !== 'production'`
from [L48](https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L48).

**Comment by jmeas** [comment]
👋  @marlonpp !

> Only thing that could change is, removing process.env.NODE_ENV !== 'production'
> from L48.

You'd want these logs in production?

**Comment by marlonpp** [comment]
That's not the case, this check is done [here](https://github.com/brigade/react-waypoint/blob/master/src/debugLog.js).

**Comment by jmeas** [comment]
Ah okay, makes sense. Perhaps the intention behind the duplicate check is so that in prod it wouldn't even make the call to `debugLog` (since that LoC would be stripped by Uglify), but I'm not sure. Perhaps @lencioni or @trotzig can shed more light there.

**Comment by lencioni** [comment]
Yep, that's the idea. https://github.com/brigade/react-waypoint/commit/d1d3ff9551d8b409e0b2a0a7588ca0f4098fc5f4
