### ISSUE TITLE
this.scrollEventListenerUnsubscribe is not a function

### ISSUE THREAD

**Issue by renanvalentin** [brigade/react-waypoint#204]
Hello!

We got this error in our production code. I tried to figure out what could be causing this but I had no success :/

```javascript 
if (this.scrollEventListenerUnsubscribe) {
  this.scrollEventListenerUnsubscribe(); // this.scrollEventListenerUnsubscribe is not a function
}
```

**Comment by trotzig** [comment]
Is it possible that you're depending on an old version of https://github.com/lencioni/consolidated-events ? The current one is 1.1.0. Before that, `addEventListener` didn't return a function.

**Comment by renanvalentin** [comment]
Seems we are using `1.1.0`. Looking at the code I couldn't find any case where `scrollEventListenerUnsubscribe` would be different from a function.

**Comment by renanvalentin** [comment]
Indeed! We are getting the old version of consolidated-events! 

<img width="383" alt="screen shot 2017-08-14 at 12 16 15 pm" src="https://user-images.githubusercontent.com/2846918/29278500-4a494cc0-80eb-11e7-99c2-ccd0e23c5eaf.png">

thanks @trotzig !

**Comment by trotzig** [comment]
Glad I could help. Did you figure out where the old version came from?
