### ISSUE TITLE
Multiple waypoint bounds

### ISSUE THREAD

**Issue by champeng** [brigade/react-waypoint#206]
Is it possible to have multiple bounds with single Waypoint component? Right now I have to nest as many Waypoint components as the number of bounds I want. By multiple bounds I mean that having multiple boundaries of the viewport so that we can receive events when elements crosses each of those boundaries.

**Comment by jmeas** [comment]
@champeng , no, each Waypoint can only have two boundaries right now.

Can you provide more information about your use case? What sort of UI are you building? How many boundaries are you trying to add? Are you running into performance issues having multiple Waypoints?

**Comment by champeng** [comment]
Thanks for the reply @jmeas. My use case is similar to  https://sarahdayan.github.io/feedify/demo.html. In addition I have one more common header on the top which is visible only when user needs it i.e. when user scrolls up. So, these things are adding complexity. The way I achieved this is by nesting 3 waypoints(bottom is same for all, only top offset is changed), one for the full viewport, another for common header's bottom and the last one for sticky header of individual item in the list. I am not sure if this is impacting the performance or not. All I can see is that it is working more or less good without much lag. However, when user scrolls too fast, I can see lag in adjusting the positions but that may be because of my code as it itself is bit complex now to handle the situation. Do we have a way to test performance for waypoints?

**Comment by trotzig** [comment]
We have [a section in the contributing document explaining how to test performance](https://github.com/brigade/react-waypoint/blob/master/CONTRIBUTING.md#testing-performance). While I was working on adding this (in ff9b7e9f901ef90) things were performing well even with a few hundred waypoints on a page. I found that the onEnter/onLeave triggering (and the position calculations associated with them) didn't really cause any issues. You are more likely to have issues if you mount/unmount many components as part of a trigger, or if you have unnecessary re-rendering. 

To find out if the three waypoints you're using is causing any perf issues, you could try replacing the waypoints with a custom scroll listener (with trigger points hard-coded) and see if you can tell any difference.

**Comment by champeng** [comment]
Thanks @trotzig for the response. I am not seeing any lag because of multiple waypoints. The only different from the performance test page and my use case is that I am using nested waypoints to achieve multiple entry-exist boundaries for the same content. I guess, it is still not causing any troubles yet. However, it would really help in organizing the code if we can support multiple boundaries in the same waypoint. That way we can make the component, using waypoint, more dynamic by passing right number of boundaries through props. As of now because of nesting, I don't have any option to avoid, when my component only needs fewer waypoints, one or many waypoints in the hierarchy. In other words, my component can be reused in different use cases, one use case is as I described in previous [comment](https://github.com/brigade/react-waypoint/issues/206#issuecomment-324580337) and another is very simple use case of having normal sticky header. So, in case of normal sticky header use case, my component is still using the 3 nested waypoints.

Hope I am clear in expressing my thoughts here.

**Comment by jmeas** [comment]
@champeng, could you use props to determine the number of Waypoints that the Component renders?

It seems like you’d need to use props even if Waypoints supported multiple boundaries, because every component you render would pass through those 5 (or whatever) boundaries unless you customized it with props, right? Or am I missin’ something :)

I’m always open to adjusting the Waypoint API to be better, but right now I’m not convinced that adding multiple boundaries is the way to go. It sounds like the current API works for you without any performance concerns, and I don’t see how multiple boundaries improves the situation.

If you’re unable to customize the waypoint structure within the component due to the way that they’re nested, then it could be worth considering if you don’t need to be nesting them. I think of Waypoints with children as being an edge case thing. I always start with waypoints _without_ children, and then only if necessary do I add children. For a long time this library didn’t even support waypoints with children!

**Comment by champeng** [comment]
@jmeas Thanks for your thoughts.

>If you’re unable to customize the waypoint structure within the component due to the way that they’re nested, then it could be worth considering if you don’t need to be nesting them. I think of Waypoints with children as being an edge case thing. I always start with waypoints without children, and then only if necessary do I add children. For a long time this library didn’t even support waypoints with children!

This seems a way to achieve my use case better. I would let you know if it still does not let me efficiently handle the use case. We can close this ticket for now, will open it if I find a use case to convince you. :)

**Comment by jmeas** [comment]
Okay, cool! We’re always learning of new and interesting use cases for Waypoints, so there’s totally a chance that you’ll run into some situation that does make sense for there to be multiple boundaries. As I said before, we’re always open to considering changes like this to the lib, so definitely do reach out to us if something comes up!

I’ll close this out for now ✌️
