### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by ntucker** [brigade/react-waypoint#213]
Probably nothing has to change but you'll need to update peerDependencies

**Comment by trotzig** [comment]
I'll be happy reviewing a PR making this change. @jmeas do you think we should bump the versions tested to 15 and 16 (in .travis.yml) or should we add another version to the mix?

**Comment by jmeas** [comment]
> @jmeas do you think we should bump the versions tested to 15 and 16 (in .travis.yml) or should we add another version to the mix?

I'm thinking we should add another version to the mix, at least for awhile. Maybe once 16 is out for a few months, and adoption starts picking up, we could drop testing 14. What do you think?

**Comment by jmeas** [comment]
@ntucker , React 16 isn't out yet (which you may already know 🙂 ), but I opened #215 in preparation for when they do cut the release.

**Comment by ntucker** [comment]
@jmeas Thanks! Yeah, typically library authors prepare compatibility in the RC timeframe of things so everything is ready on day 1 of release. :)
