### ISSUE TITLE
Calling OnEnter Only Once 

### ISSUE THREAD

**Issue by AlmahaAlmalki** [brigade/react-waypoint#216]
Hi, 

I'm trying to use waypoint to control the rendering time for visualization components, so it will be possible to see the intail animation while scrolling for the first time. However, waypoint will call onEnter every time you're inside the viewpoint. My question is is there any trick that can limit calling OnEnter for only one time. I tried to use flags, but it didn't work ... maybe I did someone wrong.

 Here's my code

```
  onWaypointEnter() {
    this.setState({hasEntered: true})
    return (
      <NetworkChart  nodes={this.state.nodesData} links={this.state.linksData} />
    )
  }
```

```
  render () {
    let waypoint = false
    
    if(!this.state.hasEntered) {
      waypoint = <Waypoint onEnter={this.onWaypointEnter}/>
    }

    return (
      <div className={'contant'}> 
          {waypoint}
      </div>
    )
  } 
```

**Comment by AlmahaAlmalki** [comment]
solved :)

**Comment by jmeas** [comment]
Oh nice! Glad you figured it out. I’ll close this issue out then.

If you want to post a little bit about what the issue was, future visitors could find it useful.

👌

**Comment by AlmahaAlmalki** [comment]
The problem was that waypoint will call OnEnter every time that you are in the viewpoint. So I will end up having multiple networks on top of each other, but it made sense this's how waypoint works. To solve this issue I added a flag and inserted waypoint in a variable. 


```
onWaypointEnter() {
    this.setState({hasEntered: true})    
  }
```

  ```
render () {

    let waypoint = false
    let viz = false
  
    if(!this.state.hasEntered) {
      waypoint = <Waypoint onEnter={this.onWaypointEnter}/>
      viz = <NetworkChart nodes={this.state.nodesData} links={this.state.linksData} />
    }
    return (
      <div className={'contant'}>
          {waypoint}
          {viz}
      </div>
    )
  }   
```

**Comment by jmeas** [comment]
Oh, cool. That makes sense, and seems like a great solution ✌️

Thanks for the follow up!
