### ISSUE TITLE
TypeScript: "..node_modules/react-waypoint/index" has no default export

### ISSUE THREAD

**Issue by sruda** [brigade/react-waypoint#224]
Hi, 
I've installed react-waypoint 7.3.1 through npm install, first of all I cannot see an **index.tsx** or **index.jsx** file (just index.d.ts type definition file).
I followed the guide including:
```jsx
import Waypoint from 'react-waypoint';
 ```
**But I receive this error:**

error TS1192: Module '"/Users/sergioruizdavila/Documents/Projects/Stylepills/stylepills-client/node_modules/react-waypoint/index"' has no default export.
![screen shot 2017-10-08 at 8 53 33 pm](https://user-images.githubusercontent.com/10075532/31323286-6b68a602-ac6b-11e7-966b-14a029872dd0.png)

Also, I tried using the import /es alternative:
```jsx
import Waypoint from 'react-waypoint/es';
```
**But the same I receive the following error:**
error TS2307: Cannot find module 'react-waypoint/es'.

![screen shot 2017-10-08 at 8 59 55 pm](https://user-images.githubusercontent.com/10075532/31323310-aeacbab6-ac6b-11e7-856e-275561d2c02a.png)

Thanks in advance

**Comment by trotzig** [comment]
Ouch, sorry about that. It's possible that we broke something for typescript users with the latest release. Any further input is valuable, I don't have a good typescript project to try this in.

**Comment by rosskevin** [comment]
There is no `default export` in the `index.d.ts`, so it seems you need to import as

```js
import * as Waypoint from 'react-waypoint'
```

I think this can be closed.

**Comment by rosskevin** [comment]
I spoke too soon.  This PR gets everything up to date
https://github.com/brigade/react-waypoint/pull/230

**Comment by nucleartux** [comment]
I think this issue can be closed.
cc @lencioni / @trotzig
