### ISSUE TITLE
Waypoint in .map'd block fires for all blocks

### ISSUE THREAD

**Issue by colinswilliams** [brigade/react-waypoint#225]
I have an array of content that I'm looking to swap out a corresponding image based on when that block is scrolled into view.

Problem I'm encountering is that when the onEnter condition is met, the function is called, but it's called for each block of mapped content.

Code looks roughly like this:

```
swapImage = image => {
    console.log(image);
}


render() {
    return (
        <div>
            {content.map(block => 
                <div>
                    <Waypoint onEnter={this.swapImage(block.image) />
                    <div>{block.content}</div>
                </div>
            )}
        </div>
    )
}
```

That console.log in image spits out the every block.image value instead of just the specific one that has been scrolled to as part of the .map.

**Comment by jmeas** [comment]
Hi there! Try this?

```diff
- <Waypoint onEnter={this.swapImage(block.image) />
+ <Waypoint onEnter={() => this.swapImage(block.image) />
```

**Comment by colinswilliams** [comment]
😂, of course, my bad, that was it.
