### ISSUE TITLE
question related to server-side-rendering

### ISSUE THREAD

**Issue by begoat** [brigade/react-waypoint#227]
This project seems to support SSR since 095ca90 .
But in my project when I render waypoint the error will occur:
```typescript
TypeError: Cannot read property 'toLowerCase' of undefined
at ReactDOMServerRenderer.renderDOM
at ReactDOMServerRenderer.render
at ReactDOMServerRenderer.read
at Object.renderToString
```

I am trying to do <i>server side rendering</i> with the help of [razzle](https://github.com/jaredpalmer/razzle). My environment is react v16.0.0 react-waypoint v7..3.1 typescript v2.3.4

I have used the correct import way
```typescript
import Waypoint from 'react-waypoint'
```

**Comment by begoat** [comment]
I tried v7.2.0 but the error still exists.
I forgot to mention the warning it gives:
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

**Comment by trotzig** [comment]
Do you think you'd be able to put together a repro case for this? Preferably a github repo that I can clone and try out locally.

**Comment by begoat** [comment]
Thank you.
Here is the min-repo https://github.com/begoat/question.git
It's a masterpiece  project build by [jaredpalmer/razzle](https://github.com/jaredpalmer/razzle)

**Comment by trotzig** [comment]
I checked it out locally and saw the same issue. I don't know what part of the build process the exports get messed up, but I tried changing `import Waypoint from 'react-waypoint'` to `const Waypoint = require('react-waypoint')` and it worked. 

I have little Typescript experience so I won't be able to help you much here unfortunately.

**Comment by begoat** [comment]
Thank you. It worked.
I will learn more about why this happened later. 
Have a nice day:)
