### ISSUE TITLE
A waypoint set on the bottom of the scrollable page fires "onEnter" on top

### ISSUE THREAD

**Issue by derwaldgeist** [brigade/react-waypoint#228]
I have a scrollable `<div>` that is set to `overflow-y: scroll`. This `<div>` is recognized correctly as the scroll ancestor, and the height is reported as the viewport's height (which is interesting; I would expect it to match its total size).

Inside this scrollable `<div>`, there are a couple of child `<div>`s that make the scrollable content, and the `<Waypoint>` comes right after these `<div>`s (but still in the container).

I would expect that the `<Waypoint>` fires `onEnter` once I scroll to the bottom. But on the contrary, `onEnter` is fired immediately (at the top), and if I scroll down, `onLeave` is fired. `onEnter` is fired again once I scroll up to the top.

If I look at the `debug` values, I can see that the waypoints' top and bottom values are at `100` once I am at the top, and they become negative (!) once I scroll down.

What might cause this behaviour?

**Comment by jmeas** [comment]
My initial guess is that this is the same as [this commonly reported issue](https://github.com/brigade/react-waypoint/issues/214). Take a look at that issue (and the other linked issues in that thread), and see if you think that's the case. If not, let us know and we'll look into this more!

**Comment by derwaldgeist** [comment]
Thanks for your fast response! I am still reading through these issues, but I doubt that the lazy loading images are causing this, because the child `<div>`s contain other content. It's actually a bootstrap grid layout. Will dig deeper into the issues, maybe I find another clue.

**Comment by derwaldgeist** [comment]
Just a guess: Has this been tested with floating `<div>`s?

**Comment by trotzig** [comment]
If you inspect the DOM, can you find the `<span>` that the waypoint renders? It's likely that it's somewhere at the top. Since you're using floats in your css, it might be enough to wrap the waypoint in something like 

```jsx
<div style={{ clear: 'both' }}>
  <Waypoint />
</div>
```

I hope we're able to find a solution to this!

**Comment by derwaldgeist** [comment]
The span is actually at the bottom of all divs (and at the bottom of the page), but I will try to use the clear approach.

**Comment by derwaldgeist** [comment]
The clear-approach worked. Thanks!

**Comment by trotzig** [comment]
Glad you got it working! Thanks for following up with your findings and for closing the ticket. 👍
