### ISSUE TITLE
Support for React 16?

### ISSUE THREAD

**Issue by cheapsteak** [brigade/react-waypoint#229]
Currently receiving the error: 

```
Error: <Waypoint> expected to receive a single React element child.
```

Tracing it back, it looks like the `children` being passed into `ensureChildrenIsValid` is always an Array, even though only one DOM element is passed in

```
<Waypoint>
  <div>...</div>
</Waypoint>
```

```js
function ensureChildrenIsValid(children) {
  if (children) {
    try {
      React.Children.only(children); // children is always an array
    } catch (e) {
      throw new Error(errorMessage);
    }
  }
}
```

**Comment by lencioni** [comment]
cc @gribnoysup

**Comment by cheapsteak** [comment]
apologies, this seems to not be react-waypoint's fault
trying to isolate what triggers the error
will post more details shortly

**Comment by cheapsteak** [comment]
Found the issue

I was using this in conjunction with react-tabs, specifically inside the `<Tabs>` wrapper but outside `<TabPanel/>`s. react-tabs seems to do some processing on the children. Taking Waypoint out of the `<Tabs/>` fixed it
