### ISSUE TITLE
docking elements

### ISSUE THREAD

**Issue by VonD** [brigade/react-waypoint#23]
Sorry if I'm missing something obvious, but how can I use this library to dock elements to the viewport ? Many thanks

**Comment by lencioni** [comment]
Thanks for your interest in react-waypoint!

With its current API, it won't really work well for docking and undocking elements to the viewport. If you wanted to do this, I think that you would need to be able to differentiate which edge the waypoint was entering or leaving, which we currently do not support. We had considered going that route when we first built this component, but decided that it would be good to keep things simple until it was needed.

If you have a proposal for a change that would make this component more useful for this use-case, we'd be happy to consider it.
