### ISSUE TITLE
Add option to disable scroll check on mount

### ISSUE THREAD

**Issue by tylerkayser** [brigade/react-waypoint#233]
I have an instance where I don't want to trigger onEnter unless there is a physical scroll by the user.  Can this be made an option?  Default settings should be the way it is currently.

Now this can be solved by a parent element that doesn't mount until scroll, but the code would be more succinct with this option in place.

**Comment by jmeas** [comment]
Thanks for the issue! I think something like this makes sense.

We could also pass something like ‘isInitial’ into the callbacks. Would that work for you? I have a slight preference for that over another prop

**Comment by tylerkayser** [comment]
That works for me!  Thanks for the quick response.

**Comment by jmeas** [comment]
As an aside, this issue vaguely reminds of #164 ,although it’s coming at it from the other angle. In #164, they want more initialization callback action, and here the ask is for less.

Anyway, @trotzig / @lencioni , what do you think of something like this?

**Comment by trotzig** [comment]
I believe `event` will be `null` when it's not triggered from a scroll. Something like

```jsx
<Waypoint 
  onEnter={({ event }) => {
   if (!event) return;
   // do your thing here
  }}
/>
```

**Comment by tylerkayser** [comment]
@trotzig's solution works!

**Comment by skirankumar7** [comment]
> Thanks for the issue! I think something like this makes sense.
> 
> We could also pass something like ‘isInitial’ into the callbacks. Would that work for you? I have a slight preference for that over another prop

is This prop available now??
reply, please...
Thanks.
