### ISSUE TITLE
support negative threshold

### ISSUE THREAD

**Issue by Guria** [brigade/react-waypoint#24]
`threshold={-1}` would allow to trigger waypoint at the top off screen

**Comment by lencioni** [comment]
Hi @Guria, thanks for the interest in react-waypoint! Will you please provide an example of what you want to accomplish with waypoint? I'm trying to understand your use-case.

**Comment by Guria** [comment]
Typical scroll-spy solution. Update selected item in navigation once header appeared at the top of screen.

**Comment by Guria** [comment]
Also suggest `offset` which will define offset in pixels. So `threshold={-1} offset={32}` would trigger when waypoint crosses 32px from top of screen

**Comment by lencioni** [comment]
For the scroll-spy solution, I wonder if a directional API would be better (see #25) than a negative threshold. That way you could determine if the element was entering or exiting from the top or bottom of the viewport. What do you think?

The `offset` prop is interesting as well. Will you please open a separate issue for that?

**Comment by lencioni** [comment]
Closing due to lack of response.
