### ISSUE TITLE
onEnter firing on load and then never again

### ISSUE THREAD

**Issue by launchriot** [brigade/react-waypoint#241]
Hi,

I've been through various issues in this repo but did not find a solution for my issue. I'm trying to set a state when the user scrolls to a specific element and thought react-waypoint could work. So far I've tried this:
```
<div styleName="content" className="col-md-6">
                            <Waypoint onEnter={self.setIndexState(0)} threshold={0}>
                                <article>
                                    <h3>Headline 1</h3>
                                    <p>Paragraph 1</p>
                                </article>
                            </Waypoint>
                            <Waypoint onEnter={self.setIndexState(1)} threshold={0}>
                                <article>
                                    <h3>Headline 2</h3>
                                    <p>Paragraph 2</p>
                                </article>
                            </Waypoint>
                            <Waypoint onEnter={self.setIndexState(2)} threshold={0}>
                                <article>
                                    <h3>Headline 3</h3>
                                    <p>Paragraph 3</p>
                                </article>
                            </Waypoint>
                 </div>
```

as well as the same thing but with the Waypoints inside of the articles (and therefor the headers and paragraphs wrapped in a span). I tried it with setting the scrollableAncestor to window and with/without the threshold as well as with/without onLeave. Right now that "setIndexState" function just fires a console.log. It fires 4 times (e.g. "set index to 0, set index to 1, set index to 2", 4 times, so a total of 12 logs) when the page loads and 0 times when I actually scroll to any of those elements. I'm using React 16.

What I'm trying to accomplish is having an image change every time a user scrolls to a different article. Thanks!

**Comment by trotzig** [comment]
Waypoints fire on page load if they are visible. Based on your example it looks like the articles don't contain much text, which would likely mean they are all visible on load. Can you share a little bit more about your setup? Perhaps a test page we can look at?

**Comment by launchriot** [comment]
The articles don't contain a lot of text, but they're pretty far down the page. I tried to make a dummy version here, although for some reason the fiddle stopped updated my changes: http://jsfiddle.net/avizuber/otrm3zxg/15/

(and thanks so much for the response)

**Comment by launchriot** [comment]
This was my issue (ES6): https://stackoverflow.com/questions/33846682/react-onclick-function-fires-on-render, I now have Waypoints working as expected. Thanks for your response.

**Comment by trotzig** [comment]
Glad you found a fix! Thanks for closing the issue once you found the fix. 👍

**Comment by JustinMoser** [comment]
Hi - Sorry to comment on this after such a long time, but I am having the exact same problem with Waypoint. Im using the latest version, however when changing pages via react router, the onEnter function doesnt get called when reaching the waypoint

- Should I open another ticket?

Thanks!
