### ISSUE TITLE
Old TypeScript definiton on npm

### ISSUE THREAD

**Issue by screendriver** [brigade/react-waypoint#245]
When I install `react-waypoint` v8.0.0 I get an old index.d.ts TypeScript definition file.

Here in the GitHub repository I see in [line 10](https://github.com/brigade/react-waypoint/blob/master/index.d.ts#L10):

```
export default Waypoint;
```

But in the package published to npm I see

```
export = Waypoint;
```

So it is not possible to use v8.0.0 in my TypeScript project anymore.

**Comment by trotzig** [comment]
Good catch! It looks like we forgot to publish that fix. I've just released 8.0.1, let me know if that doesn't fix things.

**Comment by screendriver** [comment]
Thank you. It's working now 😎
