### ISSUE TITLE
Make Waypoint directional

### ISSUE THREAD

**Issue by janpaul123** [brigade/react-waypoint#25]
E.g. provide methods or configuration so that it not just triggers when Waypoint is in the viewport (as with `onEnter`), but also when it is either above or below the viewport. This would be useful in cases where scrolling happens so fast that `onEnter` is missed (as we saw in our application).

**Comment by lencioni** [comment]
I think this is a good idea. Do you have a proposal for what the API should look like?

**Comment by janpaul123** [comment]
Yeah, not sure. What about an `onAboveViewport` and `onBelowViewport`?

**Comment by trotzig** [comment]
I'm trying to understand what problem you were experiencing. What made scrolling so fast that onEnter/onLeave wasn't fired? Was this on mobile? 

We have to be careful not to confuse people if we add these to the API.  From a glance, it isn't obvious what these two new callbacks mean.

Could we instead fix the "bug" by allowing onEnter and onLeave to be fired if we detect that scrolling was too fast?

**Comment by janpaul123** [comment]
Yeah, that might be a better option. It's impossible to always detect, e.g. if you scroll up and down again, where it was briefly in view but no scroll event was fired. But if it goes from below the viewport to above the viewport then we could detect that.

However, I wonder now if that is what actually happened. Perhaps it's also possible that the Waypoint was instantiated above the viewport in the first place, right above the loading indicators, and that it never moved through the viewport in the first place. I can look into that. In that case fixing the "bug" would not help, but the additional callbacks would.

**Comment by trotzig** [comment]
Yeah, my experience with scroll events is that desktop browsers are pretty good at firing them consistently on every pixel scrolled. I would assume most mobile browsers do too, except for iOS Safari perhaps.

**Comment by janpaul123** [comment]
Oh that's absolutely not the case. This is an example on a random webpage in Chrome:
<img width="544" alt="screen shot 2015-09-03 at 15 55 22" src="https://cloud.githubusercontent.com/assets/177461/9660109/41830b02-5254-11e5-8682-e548536ddab5.png">

**Comment by trotzig** [comment]
Yeah, you're absolutely right. Though I have a hard time seeing the quick up+down scroll not firing events close to the turning point. And even if it can happen (you're scrolling really, really fast), I don't think we can detect it. And I don't think it matters. The scenario where the waypoint was scrolled past too quickly though, we need to detect. I think keeping track of the last seen scrollY and reacting accordingly should be enough, right?

**Comment by janpaul123** [comment]
Yeah, I think so.

**Comment by trotzig** [comment]
As of a193c087b2, the direction thing is now implemented. Closing.
