### ISSUE TITLE
UI is not updating even if visible in the screen

### ISSUE THREAD

**Issue by carlocarpio** [brigade/react-waypoint#250]
I have a list of <Waypoint> component which fires an API call when is visible and update the UI if api call is finished. On initial load all the visible component is working fine as it fires the api call individually and updated the ui (values comes from the api call), but when I scrolled down to the invisible Waypoint component API call from onEnter is triggered but the UI is not updated instantly, instead UI is updated after another scroll event. 
```
_.map(items, (item, i) => {
    const user = _.find(usersActive, ['id', item])
    <Waypoint
       key={id}
       onEnter={() => this.getListValue(id)}
       fireOnRapidScroll
       bottomOffset={-500}
    >
      <div style={{ height: '160px' }}>
           { user ? <ListItem key={i} item={item} /> : <div>...Loading</div> }
       </div>
    </Waypoint>
})
```

Maybe someone can help me on why only the initial visible Waypoint Item is updating the UI after the api call while the invisible items that is initially hidden is not updating the UI even after it is visible to the screen. Thanks.

**Comment by trotzig** [comment]
Are you calling `setState` in `getListValue`?

**Comment by carlocarpio** [comment]
Update on my issue: @trotzig yes I am calling setState and that is the issue that's causing because it is not updating the UI, but when I store all the data in redux state then the UI updates as expected.

Sorry for the late reply. Thanks

**Comment by trotzig** [comment]
Okay, sounds like you at least found a workaround. I'm going to close this issue, but feel free to reopen if you still experience the issue.
