### ISSUE TITLE
Feature Request: Optionally always call onPositionChange callback

### ISSUE THREAD

**Issue by ryanbraganza** [brigade/react-waypoint#262]
Hi, I'd like to be able to always have my `onPositionChange` callback invoked. Perhaps with a new prop `onScrolled`, or an options prop.

If so, I can work on putting a PR together.

**Comment by ryanbraganza** [comment]
I have a position:fixed popup which I'd like to be automatically hidden when its parent container is scrolled (any amount) so that it doesn't appear detached from the element which triggered it.

To do this with the current Waypoint API, I believe what I would need to do is to manually measure the scrollableAncestor and calculate the appropriate top/bottom offsets such that a scroll would trigger either an enter/leave event and then invoke my handler.

**Comment by trotzig** [comment]
Assuming the scrollable ancestor in this case is the whole page, would it work to just attach a scroll listener to `window` manually? Without the waypoint I mean.

**Comment by ryanbraganza** [comment]
That would work, but I'm using the Waypoint's auto-detection of the scrollableAncestor in this case :)

**Comment by trotzig** [comment]
Ah, I see. I'd prefer not to solve this use-case with waypoint to be honest since there is a (in my mind) simpler solution. Let me know if you disagree!

**Comment by ryanbraganza** [comment]
OK. Thanks for your consideration!

**Comment by lencioni** [comment]
One option would be to extract the scrollable ancestor code into a separate package. Alternatively, you could copy it into your project. Here's what you would need I think: https://github.com/brigade/react-waypoint/blob/b06941c20643afb8a3d427f7c8d79b6ba137f2bb/src/waypoint.jsx#L129-L152

**Comment by ryanbraganza** [comment]
Thanks for the tip! For the record, the solution I went with was:

 1. add an ancestor node to the react context
 2. add/remove scroll listeners as required in the child component (defaulting to window if it wasn't found in the context)

Extracting a ScrollableAncestor component might be something I look into if I need to do something similar in a different use case.
