### ISSUE TITLE
Broken Typescript definitions?

### ISSUE THREAD

**Issue by fqlx** [brigade/react-waypoint#269]
Version: 8.0.3
When importing `react-waypoint` as `import Waypoint as 'react-waypoint'` my tests error with:
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

However, if I try to import as:
`import * as Waypoint from 'react-waypoint'`

Typescript will complain: 
`TS2604: JSX element type 'Waypoint' does not have any construct or call signatures.`

The workaround I've found is to use `7.3.4` which allows me to `import * as Waypoint from 'react-waypoint'` and my tests pass.

Are the typescript definitions broken?

**Comment by MatthewHerbst** [comment]
Might be related to https://github.com/brigade/react-waypoint/issues/238

**Comment by nucleartux** [comment]
You should do "import { Waypoint} from 'react-waypoint';".
I think this issue can be closed.
cc @lencioni / @trotzig
