### ISSUE TITLE
Allow usage of ref on custom components

### ISSUE THREAD

**Issue by clayne11** [brigade/react-waypoint#273]
React 16.3 introduced the concept of [forwarding refs](https://reactjs.org/docs/forwarding-refs.html) as a first-class citizen. We can remove the usage of `innerRef` and just use the regular `ref` prop. We can make this backwards compatible by using `innerRef` if it exists however we shouldn't throw if a custom component doesn't have `innerRef` - `ref` can work just fine.

This library currently breaks with `styled-components@4` due to this issue.

**Comment by clayne11** [comment]
Looks like we can't actually make this backwards compatible. I think we should release a new major version that no longer uses `innerRef`.

**Comment by clayne11** [comment]
@brigade-slack I'm happy to make a PR for this if you agree.

**Comment by trotzig** [comment]
I’m in favor of the breaking change. Perhaps coupled with a note in the readme about needing to use an older version for `innerRef`. Thanks for helping out!

**Comment by clayne11** [comment]
@trotzig I'm also having quite a bit of frustration with the test suite. How do you feel about updating to Jest and Enzyme? The current test suite is quite crappy to use.

**Comment by trotzig** [comment]
That sounds like a good idea in general. I remember setting this up years ago when neither of those were a thing. The only thing I would worry about is that the code relies on getting proper measurements from the browser. I’m not sure jsdom will provide those unless we mock things (which might be okay).

**Comment by clayne11** [comment]
OK I'll have a look at updating the tests in a separate PR and see how it goes.

**Comment by piuccio** [comment]
Any progress on this? I'm trying to use this library with styled-components@4 but it won't work

**Comment by clayne11** [comment]
It was a pain getting the tests working and I ran out of time working on it. I forked it and fixed it at [`@clayne/react-waypoint`](https://www.npmjs.com/package/@clayne/react-waypoint) but the tests are failing so I never submitted a PR.

**Comment by trotzig** [comment]
Is https://github.com/brigade/react-waypoint/pull/278 addressing this concern perhaps?

**Comment by twxia** [comment]
Hi @Andarist but for your change, [this line of code](https://github.com/brigade/react-waypoint/commit/3960e0d2d95845772440f4d937b7cffdc1fc3d0c#diff-06c579520a490b6292aa75be70d982b8R299) styled-compont can't get inside that condition

**Comment by twxia** [comment]
@Andarist styled-components@latest (4.1.3) I think all of v4 can't work well in that change

**Comment by Andarist** [comment]
Somehow I've made a mistake and was calling isForwardRef with wrong argument, I've prepared a PR with a fix for this just now.
