### ISSUE TITLE
Doesn't fire if it's still visible after the first onEnter

### ISSUE THREAD

**Issue by pak11273** [brigade/react-waypoint#274]
Works great on first render and fires onEnter when it's visible on the page.  But doesn't work thereafter if it's still visible on page.  Only works when the waypoint is below visible viewport after the first onEnter.   Is there a setting or workaround for this?

**Comment by trotzig** [comment]
In certain scenarios, you can use the `key` prop to force a new waypoint to be mounted. There's an example of this hidden in [the usage section in the Readme](https://github.com/brigade/react-waypoint#usage). Let me know if that resolves your issue!

**Comment by pak11273** [comment]
`key={cursor} `
Thanks!
