### ISSUE TITLE
can someone please explain what's the meaning of waypoint.below

### ISSUE THREAD

**Issue by dmcshehan** [brigade/react-waypoint#288]
` onEnter({previousPosition, currentPosition}){`
        `if(previousPosition === Waypoint.below){`
           ` this.setState({`
               ` isInView : true`
           ` });`
       ` }`
    }`

I have this code and I'm trying to understand...
`previousPosition === Waypoint.below`

this part. When I log it to the console, it just prints 'below' any explanations, please? Thanks

**Comment by trotzig** [comment]
When the waypoint is below the visible portion of the page and you scroll down so that the waypoint is now visible, then onEnter will be called with previousPosition === ’below’. Waypoint.below is a constant you can use in order to avoid using the string ”below”.
