### ISSUE TITLE
StrictMode warnings

### ISSUE THREAD

**Issue by sseppola** [brigade/react-waypoint#294]
Couldn't find an issue about this, but StrictMode results in two warnings:
<img width="638" alt="screen shot 2019-01-26 at 18 41 30" src="https://user-images.githubusercontent.com/4065840/51790806-38045900-219a-11e9-8607-f86ec683b63c.png">

The two cases are:
- https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L34
- https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L79

Which are just running checks on props.children, so it seems like it would be trivial to fix by using `componendDidMount` and `static getDerivedStateFromProps` respectively.

Let me know if there's something I'm missing, but I'd be happy to submit a PR for it if that's desired.

**Comment by MatthewHerbst** [comment]
We still support React 15, which doesn't have `getDerivedStateFromProps`. It may be worth talking about dropping 15 support.

**Comment by sseppola** [comment]
I think it would be possible to support React 15 using https://github.com/reactjs/react-lifecycles-compat

**Comment by danoc** [comment]
Hi! Any chance we can get this published? I'm happy to help if there's anything I can do.

**Comment by trotzig** [comment]
Thanks for the reminder! `react-waypoint@9.0.2` has this fix.
