### ISSUE TITLE
Note About Floated Elements

### ISSUE THREAD

**Issue by preflight** [brigade/react-waypoint#30]
React Waypoint is terrific - thanks for making it open source.

I figured out through experimentation and debugging that if the scrollable items are floated, RW can't correctly compute when to load more items. This came up when I switched to rendering my items in rows of two rather than one on top of the next. (Adding a clearfix to the container doesn't seem to have any effect.)

I wouldn't consider this a bug; it's easily worked around by setting the items to `display: inline-block` rather than `float: left`. With that adjustment, React Waypoint works perfectly.

It seems likely that others might run into this same issue; just thought I'd bring it up here in case you'd like to mention it in the docs.

**Comment by trotzig** [comment]
Hi @preflight, and thanks for using react-waypoint!

This is interesting. I've tried to reproduce your issue in a test case, but I'm coming up short. Maybe you could have a look at it and see if I'm misunderstanding something?
https://github.com/brigade/react-waypoint/commit/1abcb8cf58f9aa1bc1704d86a8629f73a8406f79

I'm making an assumption based on your report that the waypoint is rendered below the clearfix. If it is rendered inline with the floated elements, the positioning is really hard to control (I made [this jsfiddle](https://jsfiddle.net/mf4vjb0s/) to demonstrate).

**Comment by trotzig** [comment]
The reason `inline-block` works, I think, is because `<Waypoint>` is rendered as a span, thus having `inline` display style. One way to make waypoints work better with floated elements would be to allow a `style` prop to be used where the full styling of the element can be controlled. I could see that being beneficial, but it also opens up for a number of ways to abuse the component, which will make it harder to control/maintain. In any case, it would be good to know more about your specific use-case.

**Comment by lencioni** [comment]
> One way to make waypoints work better with floated elements would be to allow a `style` prop to be used where the full styling of the element can be controlled.

I don't think we would want to expand the API in this way, especially since it is easy enough to wrap it in an element that you have full style control over. 

https://medium.com/brigade-engineering/don-t-pass-css-classes-between-components-e9f7ab192785

**Comment by preflight** [comment]
Thanks for responding.

@trotzig: Your fiddle helped me realize the issue I was experiencing -- it was more a matter of me thinking of the waypoint as the "next item in queue" rather than a place marker (aka waypoint).

Since the items were floated but the waypoint wasn't, the (invisible) waypoint was rendering at the top of the list -- it was inside a clearfix, but that wouldn't do anything to force it to clear the items before it.

As shown in the updated fiddle (https://jsfiddle.net/mf4vjb0s/3/), floating the waypoint along with the items solves the issue.

I agree with @lencioni that wrapping the waypoint is the proper way of positioning/floating it vs. adding a style hook or class if one isn't already there.

**Comment by lencioni** [comment]
Thanks for following up @preflight. I'm glad we could help you sort things out.
