### ISSUE TITLE
`onEnter` and `onLeave` called twice

### ISSUE THREAD

**Issue by imouto1994** [brigade/react-waypoint#35]
Currently, I always get duplicate event handlers called when I scroll into and away from the `Waypoint`. Is there any specific requirements in the CSS?

**Comment by trotzig** [comment]
Hi @imouto1994, and thanks for using react-waypoint! This sounds like the same problem described in https://github.com/brigade/react-waypoint/issues/28. Is there anything from that thread that could help you track this down? 

We've been trying to track this bug down for a while but any attempt at recreating it has come up short. If you can provide a repro case or describe how this particular part of your app is structured, that would be really helpful.

One thing to look at is in what order the callbacks are called. Is it `onEnter` - `onLeave` - `onEnter` - `onLeave`. Or perhaps `onEnter` - `onEnter` - `onLeave` - `onLeave`?

**Comment by imouto1994** [comment]
Hi @trotzig , I think I have kinda figured out why there is duplicate call.
This happened when in `onEnter` or `onLeave` handlers, I use `setState` in the parent component containing the `Waypoint` which will trigger the `componentDidUpdate` in `Waypoint` and call `_handleScroll` again.

**Comment by trotzig** [comment]
Thanks for that information, it helps a lot actually. We have a guard to protect us from firing the same callback again by looking at the difference between currentPosition and previousPosition. But we save the previousPosition _after_ we call the onEnter/onLeave callback. Here: https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L126

I think we can resolve this by moving that line above calling the callback. We can also defer calling the callback until the next execution tick by wrapping it in a `setTimeout`. But I'm unsure what other consequences that might have. 

As a workaround, until we have this fixed and released, you can defer your setState call by wrapping it in a setTimeout.

Do you want to take a stab at creating a PR? If not, I'll get to it when I have some time over. It would be great if we can pair it with a test (spec/waypoint_spec.js).
