### ISSUE TITLE
Upgrading react to 0.14 should be considered a breaking change...?

### ISSUE THREAD

**Issue by zpratt** [brigade/react-waypoint#37]
This commit https://github.com/brigade/react-waypoint/commit/146e944a8a149a51bbbfd10a2c23a6720d8fd6c1 appears to be the culprit.

**Comment by lencioni** [comment]
Thanks for the question @zpratt! There was some discussion about this here https://github.com/brigade/react-waypoint/commit/f4dd6693074a4f148a06e2d4f2cd4c122cfab58a#commitcomment-13759022

Let us know if you still have any questions after reading that.
