### ISSUE TITLE
question: scroll position on re-render after fetching more data?

### ISSUE THREAD

**Issue by tony-kerz** [brigade/react-waypoint#50]
hi,

i'm trying to do a basic infinite scroll based on the given example,
but when i hit the waypoint and load more data, 
the scroll position resets to the first element again.

here is [a reference to a relevant spot in my project](https://github.com/tony-kerz/redux-scratch/blob/tk/scroll/app/scroll/scroll.jsx#L49).

i'm probably missing something basic, 
any guidance appreciated!

best,
tony.

**Comment by tony-kerz** [comment]
doh, nvm, i found the issue:

i was not displaying the data while an async call to the backend was active which was apparently resetting the scroll position (note the `!active &&...` bit below):

```
          <div className='panel panel-default scroll-panel'>
            <div className='panel-body greedy-height'>
              { !active && data && (
                <div>
                  {this.renderItems(data)}
                  <Waypoint
                    onEnter={this.onEnter}
                    onLeave={this.onLeave}
                    threshold={0.2}
                  />
                </div>
              )}
              { active && (
                <div>
                  <Loader loaded={false}/>
                </div>
              )}
            </div>
          </div>
```
so modifying to look something like the following resolved the issue:
```
          <div className='panel panel-default scroll-panel'>
            <div className='panel-body greedy-height'>
              { data && (
                <div>
                  {this.renderItems(data)}
                  <Waypoint
                    onEnter={this.onEnter}
                    onLeave={this.onLeave}
                    threshold={0.2}
                  />
                </div>
              )}
              { active && (
                <div>
                  <Loader loaded={false}/>
                </div>
              )}
            </div>
          </div>
```
sorry for the false alarm, leaving this here in case some other challenged person runs into similar ;)

**Comment by trotzig** [comment]
I'm glad you got it resolved. Thanks for sharing your resolution, I'm sure it will help others!

**Comment by ernest4** [comment]
This issue, omg, took longer than expected. Thank you for sharing solution!!!
