### ISSUE TITLE
Allow threshold to be different for above vs below

### ISSUE THREAD

**Issue by khankuan** [brigade/react-waypoint#56]
Currently, the threshold is assumed to be the same for both directions.

**Comment by trotzig** [comment]
This sounds like a good enhancement, but would you care to describe the use case a little bit more?

**Comment by trotzig** [comment]
The reason I ask is because it's easy to add two waypoints with different thresholds next to each other:

```jsx
<Waypoint onEnter={...} threshold={0.2} />
<Waypoint onLeave={...} threshold={0.1} />
```

Supporting different threshold for enter and leave is likely to complicate the component, and I want to make sure that we don't do it unless it's absolutely needed.

**Comment by khankuan** [comment]
Oh ok, thats a decent altenative too :)
