### ISSUE TITLE
scrollableParent prop type problem

### ISSUE THREAD

**Issue by alex-ionochkin** [brigade/react-waypoint#58]
When I set `scrollableParent` to a DOM element, `waypoint` writes a warning `Warning: Failed propType: Invalid prop scrollableParent supplied to Waypoint, expected a ReactNode.` to the browser console.
Although README says that `scrollableParent: PropTypes.any`, in fact it's `PropTypes.node` (https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L17) which causes a warning.
Can you please fix it?
In spite of warning, `scrollableParent` works as expected. Thanks for introducing it.

**Comment by trotzig** [comment]
That sounds like a bug. Any chance you could file a PR to update the code? I'll assist you if you need help!

**Comment by alex-ionochkin** [comment]
Here is a PR - https://github.com/brigade/react-waypoint/pull/59
