### ISSUE TITLE
Split Examples into Separate Pages

### ISSUE THREAD

**Issue by flarnie** [brigade/react-waypoint#6]
For the Github Page with documentation and examples, we list examples inline above the documentation currently.
Let's make them bookmarkable by giving each heading an 'id'.

This issue was revised from a previous request for separate pages, because we don't really need separate pages yet.

**Comment by flarnie** [comment]
Note: Remember to update the `README.md` directions on the `gh-pages` branch when making this change.

**Comment by lencioni** [comment]
I'm not sure we really need a landing page for all examples yet. I'd say just give the heading an ID so it can be linked to and we'll be golden.

**Comment by flarnie** [comment]
Sounds good; Updated the description above.
