### ISSUE TITLE
Suggestion: extra events

### ISSUE THREAD

**Issue by jossmac** [brigade/react-waypoint#61]
It would be nice to have information about the scroll-direction, for instance `onEnterFromBottom`

**Comment by lencioni** [comment]
What is your use-case for this?

**Comment by jossmac** [comment]
nm, got around it

Thanks for the component!

**Comment by lencioni** [comment]
I'd love to understand what you were trying to do, and what you did to get around it. Care to fill us in?

**Comment by jossmac** [comment]
Yeah, fair enough.

I was rendering a fixed masthead ("reading now", "up next" etc.) after a certain scroll distance. When the `Waypoint` enters the masthead is revealed - works great on the way down, though when you scroll back up it's hidden and then revealed again on a short enough viewport.

Got around it by measuring the `Waypoint` position and setting state only if it's negative, essentially "on the way down".

**Comment by trotzig** [comment]
The `onEnter` and `onLeave` callbacks are invoked with a second parameter that can be used to figure out the scroll direction. E.g. 

```js
<Waypoint
  onEnter={(_, from) => {
    if (from === Waypoint.above) {
      // scrolling down
    } else if (from === Waypoint.below) {
      // scrolling up
    }
  }}
  onLeave={(_, to) => {
    if (to === Waypoint.above) {
      // scrolling up
    } else if (to === Waypoint.below) {
      // scrolling down
    }
  }}
```

Would that be enough to support your use-case?

**Comment by jossmac** [comment]
That's perfect, thanks!

**Comment by trotzig** [comment]
Great! I think we need to document this a little bit better to make it more discoverable.

**Comment by jossmac** [comment]
That'd be great
