### ISSUE TITLE
Build the component into 'dist' or 'build' directory

### ISSUE THREAD

**Issue by flarnie** [brigade/react-waypoint#7]
Instead of stripping out ES6 and JSX when open sourcing a component, we should use webpack to build it into a 'dist' or 'build' directory. The 'src' directory would still have the version with ES6 and JSX, and module require statements.

Then we wouldn't have to maintain a second version of the library without require statements in the 'gh-pages' branch.

The 'griddle' repository does something similar: https://github.com/DynamicTyped/Griddle

This should be done before we release 1.0.

**Comment by flarnie** [comment]
This should be fixed by pull request https://github.com/brigade/react-waypoint/pull/12

**Comment by lencioni** [comment]
I think this is done now. Closing out. Please reopen if I overlooked something.
