### ISSUE TITLE
How to prevent onEnter from firing when scrolling back up

### ISSUE THREAD

**Issue by jcreamer898** [brigade/react-waypoint#70]
I'm working on an infinite scrolling application.

I've got it working when I scroll down and hit a way point, it's firing a redux action and adding more content.

However, I was wondering what the best way to prevent waypoints from firing again when I scroll back UP is? 

Right now, it will add a more content both when I scroll down and back up.

Any help would be awesome, thanks!

**Comment by lencioni** [comment]
You should be able to make sure that you render only one waypoint at the very end of your list. That way, when you add more content, it is added to the list and the waypoint appears after all of the items.

**Comment by jcreamer898** [comment]
Ohhhhh. Gotcha. Lemme try that quick.

**Comment by jcreamer898** [comment]
Perfect! Closing.
