### ISSUE TITLE
Error in build/npm/waypoint.js?

### ISSUE THREAD

**Issue by wnr** [brigade/react-waypoint#78]
Hello,

I believe that your build process has created an error in the built file.

At the top we find:
```
'use strict';

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactDom = require('react-dom');

var _reactDom2 = _interopRequireDefault(_reactDom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var POSITIONS = {
  above: 'above',
  inside: 'inside',
  below: 'below',
  invisible: 'invisible'
};

var propTypes = {
  // threshold is percentage of the height of the visible part of the
  // scrollable ancestor (e.g. 0.1)
  threshold: _react.PropTypes.number,
  onEnter: _react.PropTypes.func,
  onLeave: _react.PropTypes.func,
  fireOnRapidScroll: _react.PropTypes.bool,
  scrollableAncestor: _react.PropTypes.any
};
```

In the case that the result of `var _react = require('react');` is an es5 module (so that the actual React object is present at `_react.default`), the `var _react2 = _interopRequireDefault(_react);` will do nothing, as `_react.default` already exists. I'm no expert, but I guess the idea is to have all `react` accesses replaced with `_react2.default`. However, the `PropTypes` are still accessed through the original `_react` object, which throws an error since it does not contain any of the React suff. All other calls still works fine though, as they have properly been replaced with `_react2.default`. This is no problem when `_react` is exposed as a non-es5 module, since `_react` then contains all React stuff. 

Any thoughts?

**Comment by lencioni** [comment]
Sorry about this. This is my fault. I converted this to use ES6 `export` but didn't realize that Babel 6 changed it to make this inconvenient for people not using `require` instead of `import`.

The quick fix for you would be to either use `import Waypoint from 'react-waypoint';` or `.default` as you've pointed out. Long term, we should either convert this back to use `module.exports` instead of `export`, or add this Babel plugin to smooth over this for folks. https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by trotzig** [comment]
I'm a little confused @lencioni, I added the add-module-exports plugin in b7452e687. 

@wnr, could you share a bit more detail on your setup? Are you using webpack, babel or some other bundling tool? And what version of react-waypoint & react are you using?

**Comment by lencioni** [comment]
Ah, I didn't notice that. That should definitely take care of this problem.

**Comment by wnr** [comment]
Hello, and sorry for my late response.

The issue is not to require `react-waypoint`, but rather how `react-waypoint` requires `react`.

@trotzig Sure. I use browserify with Babel and all that stuff. I want to split up my code into 1) global singletons such as React and 2) my code. To do this i use `browserify -x react` to exclude the react source from my code bundle. Then I have a `react-shim.js` file that contains `export default window.React;` that gets built with browserify and told to export the `react` name with `browserify -r react-shim.js:react`. So my `index.html` file looks something like this:

```
<script src="cdn/react.js"></script>
<script src="react-shim.js></script>
<script src="app.js"></script>
```

Everything works fine, except for `react-waypoint` which throws the following error: `Uncaught TypeError: Cannot read property 'number' of undefined` at line 35 which I talked about in my first post.

If I change my `react-shim.js` file to instead export with the CommonJS syntax `module.exports = window.React;`, everything works fine. So it seems to me that the built `react-waypoint` file is dependent on `react` being exported with the CommonJS syntax, which seems like an error (probably in your build tool). Or am I missing something?

**Comment by trotzig** [comment]
I have to admit, this is a little outside my comfort zone. I wonder if @lencioni has anything thoughtful to share? 

If you are looking for a workaround in the meantime, would adding this line to the bottom of react-shim.js help?
```
module.exports = exports['default'];
```
That's what [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) does for us in our build process.

**Comment by wnr** [comment]
I have been using the `module.exports = ` as a workaround so it's not really any problem for me. Just wanted to let you know :)

**Comment by trotzig** [comment]
I'm glad that works for you. Unless others are also bitten by this, I'm don't think this is worth fixing. Others: if you end up having the same problems as @wnr, please reopen this issue!
