### ISSUE TITLE
Extremely fast scrolling doesn't work consistently

### ISSUE THREAD

**Issue by bkgunby** [brigade/react-waypoint#80]
Not sure if I can actually call this an issue because my test wasn't realistic, but I was curious: In an infinite scrolling setup without async (no `isLoading`), does waypoint sometimes break? That is, I can reach the bottom of the page when I scroll unnaturally fast. I noticed that I had to scroll back up before the threshold for it to work again.

I then tested with a `setTimeout` of something short as 10ms, and it didn't seem to have this issue. 

Again, this may or may not be an issue, but I was wondering if you guys are aware of it. If it's hardware related or something outside the scope of this library can do. Or if it's just on my end.

**Comment by bkgunby** [comment]
Closing this issue. I think it may have been just on my end of things.

**Comment by trotzig** [comment]
Thanks. I was going to point you to 2f6f047, which I added a while back to support the quick-scroll scenario you are describing.
