### ISSUE TITLE
Waypoints aren't in their correct places on initial load

### ISSUE THREAD

**Issue by bkgunby** [brigade/react-waypoint#83]
I'm not sure if this can be related to #47, but I'm facing this weird scenario when CSS styles aren't taken into account on initial load. I'm not using inline styles, maybe that's why.

For example, I've set up a waypoint after each item in a list. But when I scroll down just barely, it seems to pass the first couple of waypoints. However, I'm actually nowhere near the 2nd waypoint! But after that initial scroll, everything seems to work properly. My guess is that the CSS isn't taken into account from the beginning. 

Is there a simple fix? I'm current checking the page offset using `window.pageYOffset`, but it seems out of place.

**Comment by trotzig** [comment]
Hi @bkgunby, sorry for the late response. 

What does your list look like? A common gotcha when using waypoints are images that don't have a static height on load. Also, if you are using floats, there's a chance the waypoint is positioned at an unexpected place.

**Comment by bkgunby** [comment]
I'm using flexbox to align the images vertically, so you're probably right and possibly out of this package's scope. Closing this for now as I do have a hacky solution mentioned in my OP, but it's not as clean as I want it to be.

**Comment by trotzig** [comment]
Thanks for providing that bit of context. If you can think of ways we can detect this scenario and show a warning of some sort, let us know!
