### ISSUE TITLE
Scrolling up rapidly doesn't fire callbacks in order

### ISSUE THREAD

**Issue by bkgunby** [brigade/react-waypoint#84]
I have a scrollspy-like component so there are multiple waypoints for each section. Scrolling down quickly is fine: Each waypoint callback is being fired in the correct order no matter how quickly you scroll. But going up is a different story. Sometimes it's in order, sometimes not.

**Comment by bkgunby** [comment]
It's basically this for each item:

```javascript
<Waypoint onLeave={setCurrentPostOnLeave} threshold={-0.5} />
  <div>stuff</div>
<Waypoint onEnter={setCurrentPostOnEnter} threshold={-0.5} />

setCurrentPostOnLeave(waypoint) {
  if (
    waypoint.event &&
    waypoint.currentPosition === 'above' &&
    waypoint.previousPosition === 'inside' 
  ) {
    // set this item to active  
  }
}

setCurrentPostOnEnter(waypoint) {
  if (
    waypoint.event &&
    waypoint.currentPosition === 'inside' &&
    waypoint.previousPosition === 'above' 
  ) {
    // set this item to active  
  }
}
```

Again, all the right items becomes active no matter how fast you scroll. But in the wrong order when you scroll up rapidly. I've taken a look at the source and modified a few parts, but I'm getting nowhere unfortunately. I'll try to look into it tomorrow.

**Comment by trotzig** [comment]
Thanks for taking the time to dig in to this. May I ask why you have two waypoints for each item? Wouldn't this work:

```jsx
<div>
  <Waypoint 
    onEnter={() this.setState({ currentItem: i })} 
    onLeave={() => this.setState({})} 
  />
  <div>
    stuff
  </div>
</div>
```
?

Also, though unrelated: you don't need to check `currentPosition` in onEnter (it's always 'inside'), and you don't need to check `previousPosition` in onLeave (it's always 'inside').

**Comment by bkgunby** [comment]
The section that's taking up the most space (>50%) of the screen should be active. Scrolling down listens for the next section's top waypoint; Scrolling up listens for the previous section's bottom waypoint. It's not exactly scrollspy where I listen to the top waypoint only, but the general idea is fairly similar.

Ah you're right about the conditions. I tend to be a bit explicit when using new API's, but now I see. Thanks!

**Comment by bkgunby** [comment]
Here are some findings. 

I have a list of sections where the uppermost section has an id of `0`. Dragging the scrollbar down logs `0 1 2 3 4 5 6 7` almost always. Dragging the scrollbar up from the current position logs something like `7 6 0 1 2 3 4 5` when it should be `7 6 5 4 3 2 1 0`.

Just in case, I made sure that the list wasn't re-rendering and I took away the callback operations so it only logs. It's still having the same issue.

**Comment by bkgunby** [comment]
I've come to the conclusion it's how the browser is handling the queued events. Tried optimizing some more via `shouldComponentUpdate` and using only a single waypoint in each item like you mentioned (just realized this was possible with a single waypoint - thanks!). But nope.

Well, I'm closing this for now unless someone wants to chime in. I'd love to learn more, but I decided to go against this route for aesthetic reasons in my design.

**Comment by trotzig** [comment]
Thanks for providing all that context and for sharing your findings. The order of events is something I haven't thought too much about but it definitely matters in some situations (like the one you have/had). It's likely that this will pop up again, let me know if you can think of a clever solution.

**Comment by wursttheke** [comment]
Hey guys! Just wanted to let you know, that I am experiencing the exact same behaviour as @bryankang1308. Scrolling down works fine while scrolling up sometimes messes up the order in which the callbacks are executed.

I haven't dug into the code yet, so no clever solution from me. :/

**Comment by jmeas** [comment]
@wursttheke have you tried passing `debug={true}`? That may provide some insight into the issue. If not, post the console logs here and maybe one of us could help.

**Comment by wursttheke** [comment]
I tried it with `debug={true}` but the console output is so overwhelming, it is impossible to paste in here. 🤣 I created a simple reproduction app, though:

```
git clone https://github.com/wursttheke/waypoint-bug
npm install
npm start
```

It is just a list of containers with `onEnter` and `onLeave` callbacks. Try scrolling very fast. When scrolling down, all callbacks are fired in correct order. When scrolling up, sometimes the order is messed up. I tried it in Chrome and Safari.

Thanks for your help, everyone!

**Comment by trotzig** [comment]
@wursttheke thanks for taking the time to provide a repro repo. Can you also briefly describe the usecase here? The one I can think of where order of callbacks is important is some kind of menu where the currently active (visible) section is highlighted. Is that roughly what you have as well?

**Comment by wursttheke** [comment]
Hey @trotzig, you are spot on. That is exactly my use case. I deactivate (grey out) sections, that are not in the center of the screen. So only one section is active at all times. The ordering behaviour leads to sections not being activated again. 

It looks kind of like a typeform like this: https://freetemplate.typeform.com/to/tdFYUd
