### ISSUE TITLE
Couldn't find scroll ancestor

### ISSUE THREAD

**Issue by pebie** [brigade/react-waypoint#89]
Despite `findScrollableAncestor` is within `componentDidMount` 
React could not find Waypoint component and throw me this error :

`findDOMNode was called on an unmounted component` 

By adding a `setTimeout` around the render of my `Waypoint` component everything works fine.

My page contains a lot of thumbs and my `Waypoint` component is supposed to be render at the very bottom of these thumbs. When it will be reach, it executes a method that loads more thumbs. 

I use Redux and each page is wrapped into a `ReactCSSTransitionGroup` (it may be a clue...?)

**Comment by trotzig** [comment]
Hi @pebie! This sure is a surprising error. I can't see how the current code could result in that error. 

If you have some time, could you explore changing from `ReactDOM.findDOMNode` into using a `ref` on the rendered `<span>`? Something like this:

```jsx
_initScrollableAncestor(domNode) {
  this.scrollableAncestor = this._findScrollableAncestor(domNode);
}

render() {
  return (
    <span ref={this._initScrollableAncestor}/>
  );
}
```

You'd have to adjust `_findScrollableAncestor` to take a DOM node as an argument as well.

**Comment by pebie** [comment]
I tried. I modified the `_findScrollableAncestor` too (with domNode property etc..).

I encountered the same problem within the `currentPosition` methods. 

Using refs is worse because `_initScrollableAncestor` is called before didMount and `React.findDOMNode` should not be called on unmounted component.

What I did not understand is that the componentDidMount method is reached. So, why the node is considered not mounted by React ? oO

**Comment by pebie** [comment]
Ok so to be clear : 

If you have a component that include a Waypoint and for X reasons this component is just considered as a ReactElement (because of ReactCSSTransition or anything else), you can render the `Waypoint` usinsing `ReactDOM.render` into a specific container. By using `ReactDOM.render`, the `Waypoint` component will not throw `findDOMNode was called on an unmounted component` because `_reactInternalInstance` will not be `undefined` anymore.

I do not create a Pull Request because I think it's a specific need regarding my project. But I think it's possible to enhance `Waypoint` to avoid this kind of problem. 

BTW : Thanks for this lib that I had already used in two different project during this year :)

**Comment by trotzig** [comment]
Glad you managed to find a workaround! Thanks for sharing your problem and how you found a resolution. Hopefully it can help others having similar problems.
