### ISSUE TITLE
I can't get it to work in tables

### ISSUE THREAD

**Issue by Moezalez** [brigade/react-waypoint#90]
I have this table in which I want to use Waypoint for an infinite scrolling.

```JavaScript
<table>
  <tbody>
    <tr style={{height: '1000px'}} />
    <tr>
      <td>
        <Waypoint
          onEnter={(e) => console.log('enter', e)}
          onLeave={(e) => console.log('leave', e)}
        />
        Waypoint
      </td>
    </tr>
    <tr style={{height: '1000px'}} />
  </tbody>
</table>
```

Unfortunately, if I dont set a threshold, neither `onEnter` nor `onLeave` gets triggered at all. 
When adding `threshold={2}` I get one `enter` event and thats it.
```JavaScript
{currentPosition: "inside", previousPosition: null, event: null}
```

scrolling the Waypoint in and out won't do anything. 

Any idea?

**Comment by Moezalez** [comment]
I got it to work with jsfiddle, not sure why it's not working for me in react

**Comment by trotzig** [comment]
Interesting. Did you manage to figure out what the previous scrollable ancestor was resolved to? If so, what is the (computed) css styles for that element? I'm interested to know more because I've seen this pop up in the past. It would be good to figure out a way to prevent it.

**Comment by Moezalez** [comment]
After checking it out, I found out, that the previous scrollable ancestor was `<body>`. 
And that body had `overflow: auto;` Temporarily removing that fixed the issue, too.

**Comment by trotzig** [comment]
Do you know where that style comes from? That seems like a mistake to me, but I'm probably missing something. :)

We might be able to treat `<body>` as `window` when it ends up being `scrollableAncestor`. But I'm not sure.

**Comment by Moezalez** [comment]
No, the mistake was clearly mine. I know where the overflow: auto comes from, and it's there on purpose.

I just didn't have full understanding of the `scrollableAncestor`-mechanism and therefor just missed this.

**Comment by trotzig** [comment]
You shouldn't really need to have any understanding of the `scrollableAncestor`. It's meant to be a (mostly) hidden implementation detail. The idea is that we should be able to detect what element to attach scroll handlers to without you having to specify them. The `scrollableAncestor` prop is an escape-hatch that should only be used in rare situations. 

I think there's an opportunity to improve here. Though I'm not sure how yet.
