### ISSUE TITLE
Does not work in a scrollable box when a window doesn't have scrolls

### ISSUE THREAD

**Issue by taxigy** [brigade/react-waypoint#91]
I have a relatively positioned element, and it's scrollable:

```jsx
import React, { Component } from 'react';
import styles from './styles.scss';

export default class Whatever extends Component {
  renderSections() {
    // outputting many elements, so the parent element's content overflows
  }

  render() {
    <div className={styles.box}
      {this.renderSections()}
      <Waypoint
        onEnter={() => console.log('YAYAY!')} />
    </div>
  }
}
```

And the stylesheet is simply:

```sass
.box {
  position: relative;
  margin: 30px 0;
  padding: 0 6px 20px;
  border: 6px solid white;

  @media (min-width: 1024px) {
    height: 60vh;
    min-height: 400px;
    max-height: 1000px;
    overflow-y: scroll;
  }
}
```

On small screens (less than 1024px), the element that contains a Waypoint instance doesn't have scrolls, it's fully visible. What overflows is window. And in this case, Waypoint fires the `onEnter` callback properly. But on bigger screens, the window normally doesn't have scrolls (at least it's very unlikely), and only `.box` element is scrollable. What happens in this situation can be described in few steps:

1. Since the Waypoint is at the very bottom, a user expects the `onEnter` callback function to be fired when they scrolls to the very bottom (live example: an EULA text that is required to be fully "read").
2. User scrolls to the very bottom of the scrollable `.box`, but the event doesn't get fired.
3. Once user has _resized the window_, the event starts firing properly, no matter how many times user scrolls to the very bottom.

Another interesting case is when HMR is working:

1. A developer loads the page, scrolls to the very bottom of `.box`, nothing happens.
2. Developer changes the component code, so the component gets remounted and rendered again.
3. Starting from when the component has been remounted, Waypoint works properly, with all events getting fired as they should.

The version I'm using is 2.0.2, the latest as of today. Nothing really special isn't happening around the `.box` element and corresponding component.

**Comment by trotzig** [comment]
Interesting. Thanks for the clear repro case @taxigy. I'm assuming the media-query is somehow related. Did you get this behavior in all browsers?

**Comment by taxigy** [comment]
@trotzig works in Safari but doesn't work in Chrome, so the initial issue is only applicable to Chrome.

**Comment by trotzig** [comment]
Okay, thanks for clearing that out. So the media query doesn't seem to be involved, at least not the local one. 

We have a test that should theoretically test the scenario you are describing. The style of the parent is controlled here: https://github.com/brigade/react-waypoint/blob/dde69dd7ef19ea4e577095cd6c2cd4a0d8601349/spec/waypoint_spec.js#L34 . I tried playing around with that to see if I can create a repro case, but things are working the way they should. I've tried changing to `vh` height, adding margin, min-height etc. 

Can you try removing things from your css one by one to see if you can find what's causing this? 

Also, I pushed a new version (`2.0.3`) where you can add a `debug` prop to get some information logged to the console. It would be interesting to see if you can figure out something based on that log.

**Comment by jmeas** [comment]
@taxigy if you make a page reproducing this I'd be happy to help debug it.

**Comment by jmeas** [comment]
ping @taxigy , still having this issue? If so, care to provide more info? I'd love to see this issue get resolved :v:

**Comment by taxigy** [comment]
Updated from `@^2` to `@^3` — the issue has gone!

**Comment by jmeas** [comment]
Oh, nice! Glad to hear :)

Think this issue is good to close, then?

**Comment by trotzig** [comment]
I'm closing this based on above discussion. Feel free to reopen if you end up seeing this again @taxigy. And thanks @jmeas for helping me keep the list of open issues down to a minimum!
