### ISSUE TITLE
debug 'prop' is really needed?

### ISSUE THREAD

**Issue by bySabi** [brigade/react-waypoint#93]
IMO new `debug` prop pollute Waypoint code.

Is not really easy debug npm module??

* clone https://github.com/brigade/react-waypoint
* add `console.log` or breakpoints where ever you want in source 
* `npm link` on cloned waypoint repo
* `npm link react-waypoint` on user repo

**Comment by trotzig** [comment]
In general, I agree that debug stuff should be avoided if it's not needed. In this case however, the `debug` prop felt simple enough. 

However, I think your suggestion above is a good one too, so I added it to the README. One step missing in your list was the `babel` build step, so I added that.
